### ISSUE TITLE
Render PDF pages (PDF to image)

### ISSUE THREAD

**Issue by ahall** [unidoc/unipdf#10]
Implement a renderer for PDF pages which can be used to render pages to images.
- Based on the ContentStreamProcessor
- Should use a 2D rendering library such as https://github.com/fogleman/gg

Can be implemented in a few steps/milestones:
1. Render images.
2. Render shapes
3. Render text

The final step will be the most challenging, however, we are already building a strong foundation for font and text support which makes it possible.

Prototype code for rendering images/shapes exists in: https://github.com/unidoc/unipdf-examples/blob/v3-render-support/pdf/render/pdf_render.go

The rendering should be implemented as a package (renderer) inside unipdf.  The prototype code could used as a base and refactored into a package.

For rendering text it might make sense to start by using fonts that are available on the system or fixed local fonts.  Typically PDF viewers rely on the system fonts, as well as loading embedded fonts.

**Comment by jonnywang** [comment]
convert per page save as a image like jpg support ?

**Comment by cuihaikuo** [comment]
Any updates?

**Comment by gunnsth** [comment]
A functional prototype for this is under development. The code is in the render branch
https://github.com/unidoc/unipdf/tree/render
with examples in
https://github.com/unidoc/unipdf-examples/tree/render/render

It currently works on many PDF files, but we are still sorting out a few rendering issues that we think need to be addressed before it can be released, as well as making the API interface stable.

**Comment by gunnsth** [comment]
The renderer was released in v3.5.0. examples in https://github.com/unidoc/unipdf-examples/tree/master/render
