### ISSUE TITLE
Validation Standards PDF/A

### ISSUE THREAD

**Issue by ahall** [unidoc/unipdf#11]

**Comment by peterwilliams97** [comment]
Hi, PaperCut customers need PDF/A compliance.
Is anyone else planning to work on this? If not then I can make a proposal.

**Comment by gunnsth** [comment]
@peterwilliams97 A proposal would be very much welcome.  Our long term goal is to support this although we have not started on it yet.

Creating files with PDF/A compliant output is one thing and validation another. VeraPDF should be a good reference.

For creating files with PDF/A compliant output it might be most flexible to add something to the chain of the PDF writer that converts incompliant stuff to compliant stuff and use VeraPDF to validate.  It might be a lot of work to create a full fledged validator. Not sure.

**Comment by gunnsth** [comment]
PDF/A support is already available, see https://github.com/unidoc/unipdf-examples/tree/master/pdfa
