### ISSUE TITLE
[BUG] Calling Inspect() breaks behaviour of FlattenFields()

### ISSUE THREAD

**Issue by josh-hill-yoti** [unidoc/unipdf#119]
## Description
When `pdfReader.Inspect()` is invoked before `pdfReader.FlattenFields(), the output file is blank.

## Expected Behaviour
I expected the output PDF to have the same visible content as the input PDF.

Or if flattening is not possible I would expect an error to be returned.

## Actual Behaviour
Please see the steps to reproduce this issue and the input PDF affected in this fork of `unipdf-examples`: https://github.com/josh-hill-yoti/unipdf-examples/tree/inspect-flatten-issue/forms

The fork also includes the actual command output and output PDF I have seen.

## Workaround
The fork also demonstrates how to work around this issue by creating a new `pdfReader` for flattening.

**Comment by josh-hill-yoti** [comment]
cc @alttaf

**Comment by adrg** [comment]
@josh-hill-yoti Everything should work properly if you call `Decrypt()` on the reader before inspecting the contents. Creating a new reader is not necessary by doing it this way.

On the development branch, the sample in your repository does fail on `pdfReader.FlattenFields()` and no output file is generated. Seems like in the latest release (`v3.0.3`), no errors are reported though.

 ```go
// ................

pdfReader, err := model.NewPdfReader(f)
if err != nil {
    return err
}

ok, err := pdfReader.Decrypt(nil)
if err != nil {
    return err
}
if !ok {
    return errors.New("decrypt failed")
}

_, err = pdfReader.Inspect()
if err != nil {
    return err
}

// ................
```

**Comment by gunnsth** [comment]
@josh-hill-yoti Can you confirm that this resolves the issue?
