### ISSUE TITLE
Digital signature with an image

### ISSUE THREAD

**Issue by sayhei** [unidoc/unipdf#123]
now  i want to sign an pdf ,and i want to fill with an image,this time i only see fill with some text

**Comment by sayhei** [comment]
@gunnsth any idea? can you understand what i say?

**Comment by gunnsth** [comment]
@sayhei Yes, understood. This is not a planned feature at the moment, but we are happy to accept PRs.  Note that features that are requested by our customers receive priority.

To implement this I would recommend looking at SignatureFieldOpts in package annotator and either extending it to support images or create a new one that does.  Depends on if you want to support a combination of text and image, or how one would like to organize this.  Would be good to plan how you want to arrange this first.

**Comment by gunnsth** [comment]
See example:
https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_appearance.go
and article:
https://unidoc.io/news/applying-digital-signature-to-your-pdf

**Comment by gunnsth** [comment]
@pingyuan7 @sayhei Can you specify exactly what you are looking for?  Just a single image, or image + text?

**Comment by pingyuan7** [comment]
It can be a separate image or a text + image
spire.pdf for java 
They're packaged like this

PdfDocument doc = new PdfDocument();
doc.loadFromFile("Input.pdf");
PdfPageBase page = doc.getPages().get(0);
Rectangle2D.Float rec = new Rectangle2D.Float(100, 450, 310, 100);
PdfCertificate certificate = new PdfCertificate("gary.pfx", "e-iceblue");
PdfSignature signature = new PdfSignature(doc, page, certificate, "signature1", rec);

PdfImage img = PdfImage.fromFile("E-iceblueLogo.png");
signature.setSignImageSource(img);

signature.setNameLabel("Signer:  ");
signature.setName("Gary");
signature.setContactInfoLabel("ContactInfo:  ");
signature.setContactInfo("support@e-iceblue.com");
signature.setDateLabel("Date:  ");
signature.setDate(DateTime.getToday());
signature.setLocationInfoLabel("Location:  ");
signature.setLocationInfo("Chengdu");
signature.setReasonLabel("Reason:  ");
signature.setReason("The certificate of this document.");
signature.setDistinguishedNameLabel("DL:  ");
signature.setDistinguishedName(signature.getCertificate().get_IssuerName().getName());
signature.setGraphicMode(GraphicMode.Sign_Image_And_Sign_Detail);
signature.setDocumentPermissions(PdfCertificationFlags.Allow_Form_Fill);

**Comment by pingyuan7** [comment]
@gunnsth 
Another function is also very practical. It can be packaged independently
Divide a stamp into several parts according to the number of PDF pages, and put them on each page respectively.

**Comment by jiushicheng** [comment]
@gunnsth hi。As for the question we are discussing now, do we find a solution?

**Comment by jiushicheng** [comment]
@pingyuan7 @sayhei As for the question we are discussing now, do we find a solution?

**Comment by hongxdong** [comment]
@gunnsth Hi, Digital signature with an image is very common in China. Can you support?

**Comment by gunnsth** [comment]
@hongxdong Absolutely, this is high on our roadmap.

**Comment by gunnsth** [comment]
This is already supported, please see
https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_image_sign_appearance.go
for an example
