### ISSUE TITLE
I had to fix the glide error

### ISSUE THREAD

**Issue by snwfdhmp** [unidoc/unipdf#142]
I'm using Glide in my company project for dependency management.

I couldn't make it work with the actual implementation of unipdf (due to undesired `/v3` at the end of import path), so I fixed it and uploaded it [to my GitHub](https://github.com/snwfdhmp/unipdf) as we needed it quickly. The only change I made is to remove the `/v3` at the end of import path.

I made this a few days ago but I've just now realised that I didn't fork it but rather copy/paste in a different folder. That has prevented you from being credited when uploaded to GitHub.
That's the reason I'm here, asking you if you want me fix this by forking & making PR instead so that you're credited for the original implementation and people don't think I'm the author. Plus, I think some people might benefit from this fix.

PS: I guess that go modules will need your `/v3` import path, so maybe we shouldn't merge my fix in `master` branch, but instead create a new branch `glide-fix` and make the information available in the README so that people like me looking for the solution can find it easily.

Thanks for this cool package saving us a lot of time. My company is planning to get a PRO License when our PDF-related feature will go live (next 3 months).

**Comment by gunnsth** [comment]
Thanks.  We're considering adding a hook to our CI to automatically create a GOPATH version which would be available in a `gopath` branch (#145).  Currently both dep and glide are having issues with the go modules approach, I believe because of the /v3 in the import path.

**Comment by snwfdhmp** [comment]
@gunnsth 

>  I believe because of the /v3 in the import path.

That's right.

> We're considering adding a hook to our CI to automatically create a GOPATH version which would be available in a gopath branch (#145)

Well, it seems a good solution if you want to be able to sell your license to dep/glide users who don't want to fix themselves.

PS: Now we've got a pro license :)

**Comment by snwfdhmp** [comment]
PS : After your reply I assume you don't care about the copy-repo thing, so if I don't get any request from you about this, I will keep it as-is.
