### ISSUE TITLE
[BUG] The func (pt *PageText) sortPosition(tol float64) from extractor package is not stable.

### ISSUE THREAD

**Issue by sshxmz** [unidoc/unipdf#152]
Assume:
m1(100, 30)
m2(200, 40)
m3(300, 50)
tolerance = 15

Thus:
m1 v.s. m2, => m1 < m2 (1)
m2 v.s. m3, => m2 < m3 (2)
m1 v.s. m3, => m3 < m1 (3)

We can determine that m1 < m3 based on (1) and (2), but we get m1 > m3 from (3)。
So the sort result is not stable, it depends on the order of comparision.

**Comment by gunnsth** [comment]
Fixed by #153
