### ISSUE TITLE
[BUG] Table of contents page numbering incorrect

### ISSUE THREAD

**Issue by mrosen95** [unidoc/unipdf#154]
## Description
I am having problems with the table of contents feature. I am current running unidoc v3.0.2. All of the page numbers point to that of the master chapter, rather than the page that the subchapters are on. Additionally the hyperlinks take me to that page. 

## Expected Behavior
The page numbers in the table of contents are the actual page that the chapter or subchapter is on. 

## Actual Behavior
Heres my code for creating the table of contents. 
`
func createTableOfContents() {
	g.AddTOC = true
	toc := g.TOC()
	toc.SetLineMargins(10, 10, 3, 3)

	// Create header for the table of contents.
	headerStyle := g.NewTextStyle()
	headerStyle.Color = creator.ColorRGBFromArithmetic(0.2, 0.2, 0.2)
	headerStyle.FontSize = masterSectionFontSize
	headerStyle.Font = g.font
	toc.SetHeading("Table of Contents", headerStyle)

	// Set style of all lines in the table of contents.
	lineStyle := g.NewTextStyle()
	lineStyle.FontSize = 12
	lineStyle.Font = g.font
	toc.SetLineStyle(lineStyle)
}
`

## Attachments
[unipdf-example.pdf](https://github.com/unidoc/unipdf/files/3535155/unipdf-example.pdf)

**Comment by adrg** [comment]
@mrosen95 Would you be able to provide the entire code sample you used for creating the attached PDF file? The code you specified in the issue description does not help with reproducing the bug as it's only related to the styling of the component itself.

**Comment by gunnsth** [comment]
@mrosen95 Can you provide the entire code so we can reproduce this issue?

**Comment by mrosen95** [comment]
Sorry for the late reply. Heres the chapter builder code that we built and how it is called in our generator. Components are either tables or text. 
- Chapter Builder  
`// NewChapter creates a new PDF chapter.
func NewChapter(title, description string) *ChapterBuilder {
	return &ChapterBuilder{
		title:       title,
		description: description,
		components:  []Builder{},
	}
}

// ChapterBuilder holds information needed to generate a PDF chapter or
// sub-chapter.
type ChapterBuilder struct {
	*creator.Chapter
	title          string
	description    string
	headerFontSize float64
	parentChapter  *ChapterBuilder
	components     []Builder
}

// AddSubChapter adds a chapter under the current chapter. There is no limit
// to the number of chapter a given chapter can have. Additionally sub-chapters
// of sub-chapters are treated identically, but they appear as a lower level
// chapter in the PDF.
func (cb *ChapterBuilder) AddSubChapter(subsection *ChapterBuilder) {
	if subsection == nil {
		return
	}
	cb.components = append(cb.components, subsection)
	subsection.parentChapter = cb
}

// AddTable adds a new table to the chapter.
func (cb *ChapterBuilder) AddTable(t *TableBuilder) {
	cb.components = append(cb.components, t)
}

// Build a chapter and draw it in the PDF. This should only be called on the
// highest level chapters.
func (cb *ChapterBuilder) buildAndDrawChapter(g *RealGenerator) {
	chapter := cb.BuildDrawable(g)
	if g.c.HasErr() {
		return
	}
	err := g.Draw(chapter)
	if !g.c.NoError(err, "error while drawing chapter %s: %v", cb.title, err) {
		return
	}
}

// BuildDrawable implements the Builder interface for the Chapter Builder.
func (cb *ChapterBuilder) BuildDrawable(g *RealGenerator) creator.Drawable {
	// If the chapter has no parent chapter, it is the highest level chapter.
	// Create a new chapter with certain margins. Otherwise create a sub-chapter
	// of the parent chapter with different margins.
	if cb.parentChapter == nil {
		cb.Chapter = g.NewChapter(cb.title)
		cb.SetMargins(0, 0, 20, 0)
	} else {
		cb.Chapter = cb.parentChapter.NewSubchapter(cb.title)
		cb.SetMargins(0, 0, 10, 0)
		cb.headerFontSize = cb.parentChapter.headerFontSize - 2.
	}
	cb.GetHeading().SetFontSize(cb.headerFontSize)
	cb.GetHeading().SetFont(g.font)

	// Add chapter description.
	// Note. Styling for all chapter description is always the same regardless of
	// level (i.e. master chapter or sub-chapter of a certain depth).
	err := cb.Add(NewParagraph(g.Creator, cb.description, g.font, 12, 1.0))
	if !g.c.NoError(err, "error adding chapter description to chapter: %v", err) {
		return nil
	}

	// Iterate through all chapter components and add them to the chapter.
	for i := range cb.components {
		b := cb.components[i].BuildDrawable(g)
		switch v := b.(type) {
		// Built tables need to be added to the chapter. However sub-chapters are
		// to be added at the beginning of the build statement because of the way
		// that unidoc constructs sub-chapters.
		case *creator.Table:
			err := cb.Add(v)
			if !g.c.NoError(err, "error adding table to chapter") {
				return nil
			}
		}
	}
	return cb
}`

Called in the generator as follows
`// GenerateReport generates a PDF document based on the contents included
// in the generator and the title page builder.
func (g *RealGenerator) GenerateReport(titlePage TitlePageCreator) []byte {
	g.SetPageMargins(30, 30, 30, 30)

	g.drawTitlePage(titlePage)
	if g.c.HasErr() {
		return nil
	}

	// TODO(mrosen): update footer and table of contents to allow more variety/
	// make optional.
	drawDefaultTableOfContents(g)

	drawDefaultFooter(g)
	if g.c.HasErr() {
		return nil
	}

	for i := range g.chapters {
		g.chapters[i].buildAndDrawChapter(g)
		if g.c.HasErr() {
			return nil
		}
	}

	var writer BytesWriteSeeker
	err := g.Write(&writer)
	if !g.c.NoError(err, "Error writing PDF result to bytes: %s", err) {
		return nil
	}
	return writer.Buffer()
}

func drawDefaultTableOfContents(g *RealGenerator) {
	g.AddTOC = true
	toc := g.TOC()
	toc.SetLineMargins(10, 10, 3, 3)

	// Create header for the table of contents.
	headerStyle := g.NewTextStyle()
	headerStyle.Color = creator.ColorRGBFromArithmetic(0.2, 0.2, 0.2)
	headerStyle.FontSize = masterChapterFontSize
	headerStyle.Font = g.font
	toc.SetHeading("Table of Contents", headerStyle)

	// Set style of all lines in the table of contents.
	lineStyle := g.NewTextStyle()
	lineStyle.FontSize = 12
	lineStyle.Font = g.font
	toc.SetLineStyle(lineStyle)
}`

**Comment by mrosen95** [comment]
Adding a much more simple example. Looks like its caused by tables which span multiple tables
```
func testGeneratingTOC(env *cmdline.Env, args []string) error {
	c := creator.New()
	c.AddTOC = true

	chapt1 := c.NewChapter("Chapter 1")
	chapt1.SetMargins(0,0,20,0)

	drawCell := func(table *creator.Table, text string) {
		p := c.NewParagraph(text)

		cell := table.NewCell()
		cell.SetBorder(creator.CellBorderSideAll, creator.CellBorderStyleSingle, 1)
		cell.SetHorizontalAlignment(creator.CellHorizontalAlignmentCenter)
		cell.SetContent(p)
	}

	drawTable := func () *creator.Table {
		table := c.NewTable(3)
		table.SetMargins(0,0,5,0)
		for i := 0; i < 50;i++ {
			drawCell(table, fmt.Sprintf("cell %d-1", i))
			drawCell(table, fmt.Sprintf("cell %d-2", i))
			drawCell(table, fmt.Sprintf("cell %d-3", i))
		}
		return table
	}

	chapt1.Add(drawTable())
	chapt1.Add(drawTable())

	sc1 := chapt1.NewSubchapter("Sub Chapter 1")
	sc1.SetMargins(0,0,10,0)
	sc1.Add(drawTable())
	sc1.Add(drawTable())
	c.Draw(chapt1)

	chapt2 := c.NewChapter("Chapter 2")
	chapt2.SetMargins(0,0,20,0)
	chapt2.Add(drawTable())
	chapt2.Add(drawTable())
	c.Draw(chapt2)


	return c.WriteToFile("test-toc.pdf")
}
```

[test-toc.pdf](https://github.com/unidoc/unipdf/files/3633477/test-toc.pdf)

**Comment by gunnsth** [comment]
@mrosen95 This has been fixed in our development branch, and will be part of next release.
