### ISSUE TITLE
[BUG] No default identity encoder generated for UniGB-UCS2-H or UniGB-UCS2-V

### ISSUE THREAD

**Issue by sshxmz** [unidoc/unipdf#158]
## Description
When using an extractor to extract text from a pdf file containing font UniGB-UCS2-H, the trace says:
```
[DEBUG]  font_composite.go:200 Unhandled cmap "UniGB-UCS2-H"
[TRACE]  font.go:439 BytesToCharcodes: data=[54 08 00 20 00 20 00 20 00 20 00 20 00 20 00 20 8b a1]="T\b\x00 \x00 \x00 \x00 \x00 \x00 \x00 \x8b\xa1"
[TRACE]  font.go:704 isCIDFont: isCID=true font=FONT{`Type0` `KaiTi_GB2312` "" obj=14 ToUnicode=false flags=0x0 }
[TRACE]  font.go:704 isCIDFont: isCID=true font=FONT{`Type0` `KaiTi_GB2312` "" obj=14 ToUnicode=false flags=0x0 }
[DEBUG]  font.go:492 ERROR: No rune. code=0x5408 charcodes=[[ 5408  020  020  020  020  020  020  020  8ba1]] CID=true
	font=FONT{*model.pdfFontType0 `Type0` `KaiTi_GB2312` "" obj=14 ToUnicode=false flags=0x0  }
	encoding=%!s(<nil>)
```
Related objects got from the file for your references:
```
Resources<</XObject<</Xi0 1 0 R>>/Font<</FXF20 14 0 R/FXF21 15 0 R/Xi1 2 0 R
6 0 obj
<</Type/Font/Subtype/CIDFontType0/BaseFont/STSong-Light/FontDescriptor 5 0 R/W [1[207]6[797]9 10 374 11[423]14[375 238]17 26 462 27[238]77[228 793]]/DW 1000/CIDSystemInfo<</Registry(Adobe)/Ordering(GB1)/Supplement 4>>>>
endobj
2 0 obj
<</Type/Font/Subtype/Type0/BaseFont/STSong-Light-UniGB-UCS2-H/Encoding/UniGB-UCS2-H/DescendantFonts[6 0 R]>>
endobj
```

## Expected Behavior
Create a default indentity encoder to decode the char codes from font UniGB-UCS2.

## Attachments
I do not know how to upload the attachments privately.

**Comment by gunnsth** [comment]
@sshxmz Can you check if this is still an issue in newest version v3.4.1?  There has been some significant improvements to the CMap support, which improve text extraction a lot.

**Comment by gunnsth** [comment]
@adrg Can you check this?  I think we can close this.

**Comment by adrg** [comment]
Yes, this one should be closed. unipdf supports both `UniGB-UCS2-H` and `UniGB-UCS2-V` encodings now. While I don't have the PDF file used by @sshxmz, I did make an extraction test with another PDF using the `UniGB-UCS2-H` encoding, and the extraction was successful.
