### ISSUE TITLE
pdf_describe doesn't handle 4 bpc images

### ISSUE THREAD

**Issue by peterwilliams97** [unidoc/unipdf#16]
[A simple neural network module for relational reasoning.pdf](https://github.com/unidoc/unidoc/files/1199222/A.simple.neural.network.module.for.relational.reasoning.pdf)

**Comment by gunnsth** [comment]
Related #260

**Comment by gunnsth** [comment]
@peterwilliams97 This should be resolved now in newest unipdf versions.
