### ISSUE TITLE
[BUG] No row bytes alignment considered for image resample

### ISSUE THREAD

**Issue by sshxmz** [unidoc/unipdf#163]
## Description
No row bytes alignment considered for image resample

## Expected Behavior
Row bytes alignment should be considered when resampling image, especially for those images have BitsPerComponent less than 8. ( e.g., 1, 2, 4)
According to chapter 4.8.2 'Sample Representation' of spec 'Pdf references, version 1.7.':
> If the number of data bits per row is not a multiple of 8, the end of the row is padded with extra bits to fill the last byte.

## Actual Behavior
If the padding bits causes the sample data more than expected, the GetSample() just get the first part of resampled data (actually, the data has padding samples in each row).
I guess this is the exact reason why there are some codes to evalute the length difference between computed by resampling and expected. If the byte alignment considered correctly, the difference will disapear.
```go
// GetSamples converts the raw byte slice into samples which are stored in a uint32 bit array.
// Each sample is represented by BitsPerComponent consecutive bits in the raw data.
func (img *Image) GetSamples() []uint32 {
	samples := sampling.ResampleBytes(img.Data, int(img.BitsPerComponent))

	expectedLen := int(img.Width) * int(img.Height) * img.ColorComponents
	if len(samples) < expectedLen {
		// Return error, or fill with 0s?
		common.Log.Debug("Error: Too few samples (got %d, expecting %d)", len(samples), expectedLen)
		return samples
	} else if len(samples) > expectedLen {
		samples = samples[:expectedLen]
	}
	return samples
} 
```

**Comment by gunnsth** [comment]
@sshxmz Can you share a code snippet of a use case where this bug is actually manifested?  Necessary to verify and fix the bug.

**Comment by gunnsth** [comment]
Related #260

**Comment by gunnsth** [comment]
This should be fixed in the newest versions as part of recent improvements on this code.  Please reopen if that is not the case and include files so we can reproduce.
