### ISSUE TITLE
[FEATURE] Allow TTFParse to read from embedded asset

### ISSUE THREAD

**Issue by virtuald** [unidoc/unipdf#167]
**Is your feature request related to a problem? Please describe.**
I would like to embed a TTF font in my application to ensure that the exact font I specify is embedded in the resulting PDF.

**Describe the solution you'd like**
fonts.TtfParse should have an accompanying function that reads from an io.Reader or io.ReadSeeker, not just a file path.

**Comment by virtuald** [comment]
Never mind, I see this was done in 3.2.0

**Comment by virtuald** [comment]
Just kidding, it's not exposed anymore. I would like `model.NewPdfFontFromTTF(io.ReadSeeker)` to exist.

**Comment by gunnsth** [comment]
https://github.com/unidoc/unipdf/blob/47ae7e277ef501ca413572ab9d42fada3f87c19f/model/font_simple.go#L385
Yes it would make sense to have a `NewPdfFontFromTTF(io.ReadSeeker)` and the already exported `NewPdfFontFromTTFFile()` basically call that method.

**Comment by gunnsth** [comment]
Feel free to make a PR for this.  Should be pretty easy.
