### ISSUE TITLE
[BUG] Remove cropbox on embedded pdf

### ISSUE THREAD

**Issue by StephenMiracle** [unidoc/unipdf#168]
## Description
Our service allows users to embed a pdf inside a generated pdf. This means that we have to resize and shrink the original. This is problematic when the pdf shows a cropbox. I'd like to be able to get the page contents without the cropbox.

## Expected Behavior
function to get page contents without cropbox.

## Actual Behavior
GetPage is the only method to get contents of page and it includes the cropbox.

**Comment by gunnsth** [comment]
@StephenMiracle Can you include a self-contained example that demonstrates this?  Are you using the creator package to work with the page?

**Comment by gunnsth** [comment]
Setting or unsetting the cropbox should be pretty easy.  Missing reproduction code and files. Please reopen with files if it remains a problem.
