### ISSUE TITLE
[BUG] Protected files cannot be signed

### ISSUE THREAD

**Issue by knadh** [unidoc/unipdf#169]
## Description
A PDF that's already password protected, or one that's created with unipdf's Encrypt() can no longer be digitally signed using the Appender{}. It throws the error `page 1 not found`.

## Expected Behavior
It should be possible to open a PDF, decrypt it using Decrypt(), and use an Appender{} to apply a digital signature.

`NewPdfAppender()` makes a copy of an incoming reader https://github.com/unidoc/unipdf/blob/47ae7e277ef501ca413572ab9d42fada3f87c19f/model/appender.go#L136. It seems though that at this point, the decryption is lost. I hardcoded a `.Decrypt()` right after the copy is made and the error vanished, but the output lost all PDF contents and produced a blank page. This could potentially be due to the object comparison that happens in the update methods in the Appender.

**Comment by gunnsth** [comment]
@adrg Did #175 fix this issue also?

**Comment by adrg** [comment]
@gunnsth No, #175 solves a different issue.
@knadh Thank you for reporting the issue. We are trying to come up with a solution to treat this case.

In the meantime, as a workaround, you could use a writer to create a temporary file with no encryption and use that with the appender. What I'm suggesting is basically:
```
- Create reader of original file
- Decrypt
- Transfer everything to a new writer
- Save to a temporary file or to a memory buffer.
- Create a new reader from the previously saved file.
- Feed that to the appender.
```

**Comment by gunnsth** [comment]
@knadh Were you able to try the workaround suggested?

**Comment by knadh** [comment]
My memory is a little hazy here, but I think you would end up decrypting a password protected file and signing it, but losing password protection in the process. As in, it didn't work.

**Comment by galihrivanto** [comment]
Hi, is there any update?

I am facing same issue and workaround doesn't work. As mentioned by @knadh using workaround will losing password protection in signed file

**Comment by gunnsth** [comment]
Fixed in https://github.com/unidoc/unipdf/releases/tag/v3.29.0
See also new example https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_and_encrypt_pdf.go

**Comment by galihrivanto** [comment]
it works perfectly for me. thank you
