### ISSUE TITLE
[FEATURE] Vectorized image from SVG file for use with creator

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#179]
**Is your feature request related to a problem? Please describe.**
The use case is to load an SVG vectorized graphic and display as a vectorized graphic in PDF.
SVG is in many ways similar to the operands used in PDF content streams.

**Describe the solution you'd like**
The SVG should be converted into a PDF content stream operands.  It should be possible to apply basic transformations to it such as scaling, rotating (or apply a transformation matrix).  It would behave similar to an image such that an absolute position could be set or relative mode used.

It would make sense to focus on a subset of SVG operators as the full set is quite extensive and some operators may not make sense in PDF.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sampila** [comment]
We added basic SVG support on version https://github.com/unidoc/unipdf/releases/tag/v3.41.0

**Comment by anovik** [comment]
We added support for basic SVG transformations for version https://github.com/unidoc/unipdf/releases/tag/v3.64.0 

So basic SVG operations are now supported and I am closing this issue.
