### ISSUE TITLE
Performance: Adding paragraphs

### ISSUE THREAD

**Issue by jbuchbinder** [unidoc/unipdf#18]
With the following code, I'm seeing about 40-45ms per "paragraph" addition:

```
        p := creator.NewParagraph(content)
        p.SetFont(fonts.NewFontCourier())
        p.SetFontSize(fontSize)
        p.SetPos(xPos, yPos)
        err = c.Draw(p)
```

For building a page from small elements (50-100 elements) for multi-page documents, this can get very time-consuming. It looks as thought the performance issue is the `Draw()` method:

| Function | Execution Time |
| ----- | ----- |
| NewParagraph | 2.341µs |
| SetFont/Pos | 455ns |
| Draw | **38.043205ms** |

**Comment by gunnsth** [comment]
This has been addressed in #136 and will be in next patch release
