### ISSUE TITLE
[PROBLEM] Currency Format

### ISSUE THREAD

**Issue by drunkenmyno** [unidoc/unipdf#182]
Dear UniPDF Team,

i have a problem with a fill Form Field of my PDF File.. i just set the Format in Adobe Acrobat as as Number Format Category with Currency Symbol. But if i set the Field over unipdf i see only my number not the formatted currency..

i buld a struct 

type PDFRechnung struct {
	Name    string   `json:"name"`
	Value   string   `json:"value"`
	Options []string `json:"options"`
}

and fill a slice with this 

res1[8].Value = fmt.Sprintf("%.2f", kosten.Netto)

then i use 

err = pdfReader.AcroForm.Fill(fdata)

to fill the the data after this i use this line

fieldAppearance := annotator.FieldAppearance{OnlyIfMissing: true, RegenerateTextFields: true}

	err = pdfReader.FlattenFields(true, fieldAppearance)
	if err != nil {
		log.Println(err)
	}

did i miss something ?

**Comment by gunnsth** [comment]
@drunkenmyno Can you contribute a PDF file and code so this can be reproduced?

**Comment by gunnsth** [comment]
Most likely this would be resolved by selecting a font having the right glyphs. Please reopen with the file if this comes up.
