### ISSUE TITLE
[FEATURE] Ability to underline text

### ISSUE THREAD

**Issue by becoded** [unidoc/unipdf#184]
**Is your feature request related to a problem? Please describe.**
At this point, there is no easy way to underline some words in a paragraph

**Describe the solution you'd like**
It would be great, that you could just do 
```
customStyle := c.NewTextStyle()
customStyle.Underline = true
```

**Comment by polderudo** [comment]
Any update on this? Underlining is realy important for some report types

**Comment by gunnsth** [comment]
This is in our plans, cannot say exactly when, but soon.  Can contact our sales and support if you urgently need prioritisation of this or any other issue.

**Comment by gunnsth** [comment]
Underlining feature has been added in v3.18.0. Example:
https://github.com/unidoc/unipdf-examples/blob/master/report/pdf_formatted_text.go
