### ISSUE TITLE
[BUG] extractPageText crashes

### ISSUE THREAD

**Issue by Kleissner** [unidoc/unipdf#192]
## Description
https://github.com/unidoc/unipdf/blob/76a1225d32f4ea5881b3f643b82ff11c91cc525f/extractor/text.go#L112-L114

In the function `extractPageText` you are using `to.marks` _without_ checking if `to` is nil or not. If the PDF has this "ET" (end text) marker without the "BT" (begin text) marker, the code will crash.

This is actually a problem throughout the function, the `to` variable is referenced many times without checking if it's nil.

```
2019/10/22 00:45:51 Error: Panic of monitored 'Sample.exe': panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x140 pc=0xb2f233]

goroutine 150 [running]:
github.com/unidoc/unipdf/extractor.(*Extractor).extractPageText.func1(0xc0012602d0, 0xe9b500, 0x15292c0, 0xe9b500, 0x15292c0, 0xc753a0, 0xc001b85428, 0xc753a0, 0xc001b85430, 0x3ff0000000000000, ...)
	C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:113 +0x1f93
github.com/unidoc/unipdf/contentstream.(*ContentStreamProcessor).Process(0xc001559748, 0xc001af7dd0, 0x0, 0x0)
	C:/Temp/Go/src/github.com/unidoc/unipdf/contentstream/processor.go:272 +0x5ac
github.com/unidoc/unipdf/extractor.(*Extractor).extractPageText(0xc000de4b00, 0xc00149c000, 0x5f34, 0xc001af7dd0, 0x0, 0x140008, 0x0, 0xc00149c000, 0xc0009fe000, 0x140008)
	C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:324 +0x52b
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractPageText(0xc000de4b00, 0x40e3e4, 0xd0bbc0, 0xc0013240f0, 0xc0021db928, 0xb20a5b)
	C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:45 +0x5c
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractTextWithStats(0xc000de4b00, 0xc000de4b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:36 +0x39
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractText(...)
	C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:29
```

## Expected Behavior

Obviously, a corrupt or invalid PDF (like one with an "ET" marker but not a "BT") should not result in a crash. Instead, the function should return with an error.

**Comment by Kleissner** [comment]
This is the file that causes the crash: [ba55d87e-0441-44a3-a6c7-d47a65d6efc1.pdf](https://github.com/unidoc/unipdf/files/3772166/ba55d87e-0441-44a3-a6c7-d47a65d6efc1.pdf)

**Comment by gunnsth** [comment]
@Kleissner Can you confirm that this fixes the problem and close if so?

**Comment by Kleissner** [comment]
I confirm, it is no longer crashing and returns the text now.
