### ISSUE TITLE
[BUG] 32 bit windows issue

### ISSUE THREAD

**Issue by tsxylhs** [unidoc/unipdf#197]
## Description

32 bits cannot be packed
## Expected Behavior
Package under 32-bit Windows

**Comment by gunnsth** [comment]
Can you post some code that we can try?  and commands to execute to reproduce?  What is the error?

**Comment by ahall** [comment]
This 32 bit issue was resolved in later versions. 3.2.0 and 3.3.0 work ok on 32 bit.
