### ISSUE TITLE
Configure Rotation Origin

### ISSUE THREAD

**Issue by jcampbell05** [unidoc/unipdf#20]
We have code to scale down PDFs to A4 documents and center them, as part of this we want to output a portrait PDF. If the input PDF was landscape this means they end up much smaller so we want to make sure they are 90 degrees rotate so they benefit from having as much space as possible.

In the current API it rotates from some sort of origin the library defaults to, we looked through the code and it looks like the only way to control this is to hack it by doing some translation before rotating.

I noticed you have a TODO to control the origin which we would be interested in as we want to be able to control it so we can simply rotate by 90 degrees and center it (The centering code completely breaks at the moment as it assumes the origin is in the middle.

**Comment by gunnsth** [comment]
Closing.  The planned behavior is to have the center of rotation at the center of the object for all objects. The SetPos and GetPos will refer to the upper left corner of an object.
If there are use cases for a configurable rotation origin please comment on this issue and we can reconsider this.
