### ISSUE TITLE
[FEATURE] Row span for table

### ISSUE THREAD

**Issue by schooltech** [unidoc/unipdf#201]
Hi,

For the processing of the table, I see an example of colspan, I don't know if it is possible to implement rowspan?

Best regards,
David

**Comment by schooltech** [comment]
hi @gunnsth , unipdf now can support to set row span now?

**Comment by gunnsth** [comment]
This has been added in https://github.com/unidoc/unipdf/releases/tag/v3.27.0
See functions `MultiRowCell` and `MultiCell` on `creator.Table` type.
