### ISSUE TITLE
[FEATURE] Support generating text with emojis

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#206]
**Is your feature request related to a problem? Please describe.**
Support creating text with emoji's in it.

**Describe the solution you'd like**
With the creator, should be able to load a font such as "Segoe UI Emoji" and draw emoji's as glyphs via Paragraph and StyledParagraph.

**Describe alternatives you've considered**
This might work already, needs some research of what encoding those fonts use for the emojis.  Expected to be UTF-16 identity mapping with a composite font.

**Additional context**
Came up in https://github.com/unidoc/unipdf-examples/issues/71

**Comment by gunnsth** [comment]
Example play using emojis:
https://play.unidoc.io/p/3ccab4b33e6b58c5

**Comment by gunnsth** [comment]
As shown in the play above, emojis are supported. Closing.

**Comment by rogchap** [comment]
@gunnsth This is not true Emoji (Unicode) support; text based symbols are different from an emoji: 😀 vs ☻
If there was a way to do an image replacement for an emoji character set, that would be the best way to support Emojis.

**Comment by rogchap** [comment]
On further investigation it also seems that an Emoji font, like Noto Emoji, fails to render: https://www.google.com/get/noto/#emoji-zsye Composite or otherwise.
