### ISSUE TITLE
Improper handling of 1 bit images when converting to native go images

### ISSUE THREAD

**Issue by plaisted** [unidoc/unipdf#21]
Extracting 1 bit grayscale images from a pdf and using `ToGoImage()` result in 8bit golang grayscale images with 0 for black (correct) but 1 for white (instead of 255). The rest of the extraction appears to be correct.

Code in `ToGoImage()`:
```golang
if this.ColorComponents == 1 {
    if this.BitsPerComponent == 16 {
        val := uint16(samples[i])<<8 | uint16(samples[i+1])
        c = gocolor.Gray16{val}
    } else {
        val := uint8(samples[i] & 0xff)
        c = gocolor.Gray{val}
    }
}
```
Switching `val := uint8(samples[i] & 0xff)` to `val := uint8(samples[i] * uint32(256 / this.BitsPerComponent-1))` resolves the issue for 1 bit images but haven't tested it for other cases.

**Comment by adrg** [comment]
Is this still an issue? 

The latest version of the code for handling gray scale image data looks good to me. I'll post here the relevant part of the `ToGoImage` method:
```
if img.ColorComponents == 1 {
    if img.BitsPerComponent == 16 {
        val := uint16(samples[i])<<8 | uint16(samples[i+1])
        c = gocolor.Gray16{val}
    } else {
        val := samples[i] * 255 / uint32(math.Pow(2, float64(img.BitsPerComponent))-1)
        c = gocolor.Gray{uint8(val & 0xff)}
    }
}
```

**Comment by gunnsth** [comment]
OK that looks correct.  Closing.
