### ISSUE TITLE
[BUG] Rendering issue where image content is blacked out

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#212]
## Description
When rendering the attached PDF, the raster image is blacked out, as can be seen below.

## Expected Behavior
Expected rendering:
![image](https://user-images.githubusercontent.com/50777/70853133-d0cec080-1ea1-11ea-8a5a-e062fac8e379.png)

## Actual Behavior
I used the PDF rendering example: https://github.com/unidoc/unipdf-examples/blob/render/render/pdf_image_render.go to render the file 004_text_display.pdf and got:
![004_text_display_1](https://user-images.githubusercontent.com/50777/70853135-d75d3800-1ea1-11ea-9f59-35e08950e07c.png)

## Attachments
[004_text_display.pdf](https://github.com/unidoc/unipdf/files/3964204/004_text_display.pdf)

**Comment by gunnsth** [comment]
This is still a problem in v3.17.0.

**Comment by Sarah-clariondoor** [comment]
This might be the same or similar issue that I am experiencing. When I run the DEC Coverage Limitation.pdf file through the pdf_image_render.go example, it creates a png image with a square-ish shaped blob at the top left corner.

[example.pdf](https://github.com/unidoc/unipdf/files/5883587/example.pdf)
![example_1](https://user-images.githubusercontent.com/42549181/106064423-ad1f0780-60ae-11eb-8c83-b47e1324dbe0.png)

I ran the OP's pdf through as well and got something different than the OP stated, but still not expected. Attached for convenience.

![004_text_display_1](https://user-images.githubusercontent.com/42549181/106064166-3d108180-60ae-11eb-848c-5755ad7b5ac2.png)

**Comment by Sarah-clariondoor** [comment]
Update: pdf was rendering in my code base just fine after upgrading go to version 1.14 and upgrading unidoc.unipdf to v3.18.0. I did not try it in the unipdf-example.

**Comment by gunnsth** [comment]
The originally posted file still having a problem in v3.18.0.

**Comment by Sarah-clariondoor** [comment]
Second update: pdf is rendering, but formatting is off and words are different sizes or cut off. PDF file and PNG image rendered through unipdf-examples pdf_image_render attached for reference
[single.pdf](https://github.com/unidoc/unipdf/files/5998371/single.pdf)
![single_1](https://user-images.githubusercontent.com/42549181/108263041-95212d80-711a-11eb-8493-b1e38cf6c127.png)

I ran the OP's PDF through as well and got the same result as OP. 

I am using Go version 1.14 and unipdf v3.19.0.

**Comment by sampila** [comment]
Hi @sarah-schmidt,

We released new UniPDF version v3.53.0 https://github.com/unidoc/unipdf/releases/tag/v3.53.0, could you try to update the UniPDF version and see if this issue is resolved?

Best regards,
Alip

**Comment by dillonkh** [comment]
Hi @sampila I have been running into the same problem with v3.53.0. I stepped back versions from v3.53.0 to try and see if it was a new bug and turns out v3.51.0 does **not** have this issue, but v3.52.0 and v3.53.0 do.
The catch is v3.51.0 does not seem to support decoding and encoding with JPX 😞
```
p, err := pdf.NewPdfReader(r)
if err != nil {
	return nil, err
}

numPages, err := p.GetNumPages()
if err != nil {
	return nil, err
}

c := creator.New()

for i := 1; i <= numPages; i++ {
	// get page from pdf
	page, err := p.GetPage(i)
	if err != nil {
		return nil, err
	}
        
	s, err := c.NewImageFromGoImage(img) // img is a goimage (png with transparency)
	if err != nil {
		return nil, err
	}

	// add page to new pdf
	c.AddPage(page)

	err = c.Draw(s)
	if err != nil {
		return nil, err
	}
}

// create output buffer
b := new(bytes.Buffer)

// write pdf to output buffer
c.Write(b)

return b, nil
```
[v3-51-0.pdf](https://github.com/unidoc/unipdf/files/13822336/v3-51-0.pdf)
[v3-53-0.pdf](https://github.com/unidoc/unipdf/files/13822337/v3-53-0.pdf)
![original-img](https://github.com/unidoc/unipdf/assets/43145893/7eaff3cc-f545-43f0-ba80-925e897a0201)
(NOTE the web viewer my make the pdf look even worse...)

**Comment by sampila** [comment]
Hi @dillonkh 

From version v3.52.0, we changes the default encoder to DCTEncoder, to solve this, you can set the encoder into flate encoder, the code will be like this

```
p, err := pdf.NewPdfReader(r)
if err != nil {
	return nil, err
}

numPages, err := p.GetNumPages()
if err != nil {
	return nil, err
}

c := creator.New()

for i := 1; i <= numPages; i++ {
	// get page from pdf
	page, err := p.GetPage(i)
	if err != nil {
		return nil, err
	}
        
	s, err := c.NewImageFromGoImage(img) // img is a goimage (png with transparency)
	if err != nil {
		return nil, err
	}
        
        // Set go image encoder to Flate encoder.
        s.SetEncoder(core.NewFlateEncoder())

	// add page to new pdf
	c.AddPage(page)

	err = c.Draw(s)
	if err != nil {
		return nil, err
	}
}

// create output buffer
b := new(bytes.Buffer)

// write pdf to output buffer
c.Write(b)

return b, nil
```
Could you try to run the code and see the results?

**Comment by dillonkh** [comment]
@sampila that did the trick! 🙌

**Comment by sampila** [comment]
Hi @dillonkh,

As this is resolved, we closing this issue for now.

Best regards
