### ISSUE TITLE
Create model.PdfCatalog type

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#22]
Create a model.PdfCatalog type
```go
// PdfCatalog represents the root Catalog dictionary (section 7.7.2 p. 79)
type PdfCatalog struct {
    Type *core.PdfObjectName
    Version *core.PdfObjectName
etc...
}
```
Will make it easier to work with externally and simplify usage within the model package.

**Comment by anovik** [comment]
Now we have Catalog type in model/internal/docutil https://github.com/unidoc/unipdf/blob/master/model/internal/docutil/docutil.go with getters and setters for data like version, metadata, etc.
