### ISSUE TITLE
[BUG] Removed whole paragraph when one glyph missed

### ISSUE THREAD

**Issue by mchusovlianov** [unidoc/unipdf#220]
## Description
Hi, y'all! I'm not sure if this behaviour is bug or not. Is there any reason to stop render text when found unsupported rune? I expected to have that rune just removed. There are a lot of fonts which not support emojis and some special characters. Is there a way how can we impact on this behaviour? 
```
//paragraph.go:501
code, ok := enc.RuneToCharcode(r)
if !ok {
	err := fmt.Errorf("unsupported rune in text encoding: %#x (%c)", r, r)
	common.Log.Debug("%s", err)
	return ctx, err
}
```

**Comment by gunnsth** [comment]
@mchusovlianov Can you please share self-contained example code with us, so we can run it and reproduce exactly?  Are you using newest unipdf version?  The expected behavior is to ignore missing/unsupported rune.

**Comment by gunnsth** [comment]
@mchusovlianov This should not be a problem if you are using the newest unipdf.  Please confirm what version you are using.

**Comment by mchusovlianov** [comment]
@gunnsth  My bad! I'm sorry for bothering you! In the latest version it works like a charm. Thanks for your job!
