### ISSUE TITLE
[BUG] Problem filing form fields with chinese - the content is missing

### ISSUE THREAD

**Issue by sayhei** [unidoc/unipdf#221]
## Description
first i fill chinese in form fields,then iflatten form data in PDF files. the chineses is missing  ,however the number and English alphabet is fine.

**Comment by gunnsth** [comment]
@sayhei  Please follow the issue template and provide a self-contained example: https://github.com/unidoc/unipdf/issues/new?assignees=&labels=&template=bug_report.md
Also include information regarding what version of unipdf you are using.

**Comment by gunnsth** [comment]
Closing as missing data.  Please include the detail when reopening the issue
