### ISSUE TITLE
[BUG] Rendering issue: Type3 fonts are not currently supported

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#235]
## Description
When rendering the attached PDF there is an error.  Problem seems to be lack of support for rendering Type 3 fonts.
Type 3 fonts have glyphs stored as PDF objects (content stream), so it should be fairly easy to support going forward.

## Expected Behavior
Expected to run without issues and create an image rendering of the PDF page.

## Actual Behavior
1, Run the rendering example
```
$ ./pdf_image_render out image_cliprect.pdf
2020/01/22 18:56:25 Image rendering error: Type3 fonts are not currently supported
```

## Attachments
[image_cliprect.pdf](https://github.com/unidoc/unipdf/files/4099325/image_cliprect.pdf)

**Comment by 3ace** [comment]
@gunnsth I think this should no longer be an issue in latest code. here is the result of running the `pdf_image_render.go` against the attached pdf file

![image_cliprect_1](https://github.com/user-attachments/assets/1c19d4b2-e3a2-45ef-8d8e-55c448f52368)

**Comment by gunnsth** [comment]
Great, closing this then.
