### ISSUE TITLE
[FEATURE] Make transform package non-internal

### ISSUE THREAD

**Issue by divan** [unidoc/unipdf#251]
I'm playing around with `extractor` package and want slightly different functionality, so I created own package where I use most of the extractor code as a bootstrap and implement my logic. However, `extractor` code imports `internal/transform` package which makes it impossible to use outside of `unipdf` module.

It seems to be no real reason why `transform` package should be internal, so I propose to make it normal subpackage, available for import from the third-party code. I tested it with the fork, the changes are minimal (only 4 imports need to be changed), and it solves my use case.

**Comment by gunnsth** [comment]
Hi @divan Can you share more about your specific use case?  That would be helpful.

The reason why `transform` and a few other packages are internal is because they are not expected to be needed externally and exporting them would make it less flexible for us to change the internals of exported methods etc.  That is, harder to try to keep API compatibility.

**Comment by divan** [comment]
Sure. I'm parsing one specific type of legacy PDF documents for further data extraction. For that I build my own structure of "words" – similar to the `textMarks`, but where "words" actually mean values of `Tj` (and other text rendering) commands. I know that won't work for 100% general of use cases, but it works perfectly for this particular documents corpus.

Current implementation of textMarks breaks every Tj string into runes, while I need to preserve these boundaries, because they hold structural information of the document which is lost otherwise.

I see the point of why `transform` is internal now. Do you think it's going to have breaking changes in the future? It seems to be quite small and stable from the first glance.

**Comment by gunnsth** [comment]
Thanks for the input.  Sounds like you are doing something pretty low level that we would hopefully like to be able to support better in the `extractor` package with higher level functions.

For your purpose it sounds like forking and working inside the library might sense.  If you have something you think is useful to others and could be exported, please feel free to make a PR for evaluation.

I am not sure regarding `transform` but would certainly like to have the flexibility to change it when needed.  The extractor package is still undergoing big changes and we are working on improvements to the text extraction etc.

**Comment by divan** [comment]
Thank you, got your points. Using fork is working for me, yes.

As a side note, after working for years with other PDF libraries for Go, I'm so impressed with Unidoc/Unipdf library and the overall quality of the code – it's just another league. I really wish I could use it in my commercial projects as well and fiercely recommend to other people – but can't do it now due to the prohibitively high licensing price. Anyway, terrific work!
