### ISSUE TITLE
[FEATURE] Create StyledParagraph from html markup string

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#261]
**Is your feature request related to a problem? Please describe.**
Currently creating StyledParagraphs consists of quite many steps.  It would be nice to have a way to create those more easily, for example from some limited html or markdown support.  

**Describe the solution you'd like**
For simple things it would be nice to be able to do:
```go
spara, err := NewStyledParagraphFromHTML("This is <b>bold</b><br/>newline with <i>italic</i>")
```
also should support some kind of basic styling for colors and changing font widths etc.  It would be focused on styled paragraphs, so not including lists, tables etc.

HTML is a nice choice since most developers are familiar with it.  Although, the disadvantage is that it would probably look different from something in a web browser.

It would also be necessary to specify some `options` to specify what fonts to use for bold, italic, etc and some other default properties.

**Describe alternatives you've considered**
Markdown would be another alternative, but not quite as commonly used.  Also the golang standard library has a html parser that could be used, so no extra dependencies.

**Additional context**
This idea was spawned via discussions with clients that have an input form on a website that allows some markup that they would like to use in PDFs that are produced by their backend.

**Comment by bgunner** [comment]
Hey! 
That kind of functionality would be awesome! We do need this in our system.
I know that we can use the creators component but as we need this styling to be dynamical, using the creators component would be really hard.

**Comment by gunnsth** [comment]
PR: #277

**Comment by gunnsth** [comment]
Closed as we decided to go the way of having UniHTML support a full renderer.
We may consider adding a more lightweight markup language in the future.
