### ISSUE TITLE
Can you provide an example of PDF image signature？

### ISSUE THREAD

**Issue by pingyuan7** [unidoc/unipdf#262]
Can you provide an example of PDF image signature？

**Comment by gunnsth** [comment]
Please see:
https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_appearance.go
and also as demonstrated in:
https://unidoc.io/news/applying-digital-signature-to-your-pdf

**Comment by pingyuan7** [comment]
Maybe I didn't make it clear.
What I want is an electronic signature. Attach a picture to the digital signature.
Is there a way to do it?

**Comment by gunnsth** [comment]
Ah. Duplicate of #123

**Comment by pingyuan7** [comment]
It can be a separate image or a text + image
spire.pdf for java
They're packaged like this

PdfDocument doc = new PdfDocument();
doc.loadFromFile("Input.pdf");
PdfPageBase page = doc.getPages().get(0);
Rectangle2D.Float rec = new Rectangle2D.Float(100, 450, 310, 100);
PdfCertificate certificate = new PdfCertificate("gary.pfx", "e-iceblue");
PdfSignature signature = new PdfSignature(doc, page, certificate, "signature1", rec);

PdfImage img = PdfImage.fromFile("E-iceblueLogo.png");
signature.setSignImageSource(img);

signature.setNameLabel("Signer: ");
signature.setName("Gary");
signature.setContactInfoLabel("ContactInfo: ");
signature.setContactInfo("support@e-iceblue.com");
signature.setDateLabel("Date: ");
signature.setDate(DateTime.getToday());
signature.setLocationInfoLabel("Location: ");
signature.setLocationInfo("Chengdu");
signature.setReasonLabel("Reason: ");
signature.setReason("The certificate of this document.");
signature.setDistinguishedNameLabel("DL: ");
signature.setDistinguishedName(signature.getCertificate().get_IssuerName().getName());
signature.setGraphicMode(GraphicMode.Sign_Image_And_Sign_Detail);
signature.setDocumentPermissions(PdfCertificationFlags.Allow_Form_Fill);


@gunnsth
Another function is also very practical. It can be packaged independently
Divide a stamp into several parts according to the number of PDF pages, and put them on each page respectively.
