### ISSUE TITLE
How to use UTF8 Font.

### ISSUE THREAD

**Issue by riseres** [unidoc/unipdf#282]
I have try this library. and I want to use Thai Font.
I have changed to Thaifont.tff file. 

using  model.NewPdfFontFromTTFFile(.....)

as follow in createPDF example. 
The result is blank Thai font. 

let's me know how to use UTF font.

**Comment by adrg** [comment]
Hi @riseres. Try using `model.NewCompositePdfFontFromTTFFile` instead of `model.NewPdfFontFromTTFFile` when loading your font.

**Comment by riseres** [comment]
Thank you.

It works
