### ISSUE TITLE
Signing with certificate chain

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#284]
## Description
An inquiry was received via email:

> I tried to sign pdf file with UniPdf and I faced to problem. According to this example https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_hsm_pkcs11.go I can sign document with one certificate but in my case I have a certificates chain. The chain consist of 3 elements and stored in one file, something like this
```
-----BEGIN CERTIFICATE-----
.....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
.....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
.....
-----END CERTIFICATE-----
```

Also I have a private key store in HSM.

It is possible to sign document with such kind of certificate chain by using UniPdf? Could you provide a simple example if it is possible?

**Comment by PmgFranco** [comment]
I'm also looking into possibly buying the license in the future and this would be an important use case. More examples would be greatly appreciated.

**Comment by gunnsth** [comment]
@adrg Can you comment on how this was achieved?  And possibly add another example to
https://github.com/unidoc/unipdf-examples/tree/master/signatures
maybe something like pdf_sign_multicert.go or something like that.

**Comment by gunnsth** [comment]
We have added an example showing how to achieve this, closing.
https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_pem_multicert.go
