### ISSUE TITLE
model.SetPdfAuthor when editing files concurrently

### ISSUE THREAD

**Issue by advanderveer** [unidoc/unipdf#285]
First, off congratulations with this great library! I'm experimenting around with it to get a feel for its API but the model.SetPdf* methods strike me as odd. As far as I understand the source code, these functions set global variables which are then used during the writing of pdf files. I'm trying to read and write pdf files concurrently (in the same program) and this means that I need to set these values (Author, creator etc) per model.PdfWriter not globally.

How can I achieve this,  am I missing something?

**Comment by gunnsth** [comment]
@adrg What do you think?  Might make sense that those global values serve as the default but can be changed per Writer instance?

**Comment by adrg** [comment]
Yes, this seems like a good idea. We could provide the same setter methods as the global ones and write directly to the info dictionary of the writer instance.

**Comment by gunnsth** [comment]
This has been fixed already. And also can now set on a document basis, see https://github.com/unidoc/unipdf-examples/tree/master/metadata
