### ISSUE TITLE
How can I know more technical details of pdf

### ISSUE THREAD

**Issue by sayhei** [unidoc/unipdf#311]
When I want to help solve the problems I have found, I find that I know too little about pdf. Are there any books or articles that introduce more details of pdf technology

**Comment by gunnsth** [comment]
@sayhei The best reference is the PDF reference: 
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

There is a newer version PDF 2.0 ISO standard available for purchase: https://www.iso.org/standard/63534.html

We find that the PDF32000_2008.pdf is sufficient in most cases, except in cases where the standard has been updated (such as encryption types etc).
