### ISSUE TITLE
[BUG] pdfWriter.Write() should return err != nil on errors to io.Writer

### ISSUE THREAD

**Issue by ahawtho** [unidoc/unipdf#316]
## Description
`PdfWriter.Write()` writes to an `io.Writer`, but never checks the return value of any of the calls to its internal `bufio.Write*()` calls.

## Expected Behavior
I have a test that intends to verify that failed writes can be retried when writing to certain media that may fail (network write). I was surprised when my test failed. After debugging, the reason it failed was because the `PdfWriter.Write()` method wasn't actually returning a failure although the test was returning errors from the mock `io.Writer.Write()` method.

## Actual Behavior
1. Invoke PdfWriter.Write() with a Writer that returns an error
2. Receive a nil error response.

## Attachments
Include a self-contained reproducible code snippet and PDF file that demonstrates the issue.

[unipdf-bug.zip](https://github.com/unidoc/unipdf/files/4495341/unipdf-bug.zip)

**Comment by gunnsth** [comment]
@ahawtho Thanks for reporting.  A PR has been created to address this:
https://github.com/unidoc/unipdf/pull/320
Will be reviewed, then merged into development and then become released early next week.
