### ISSUE TITLE
v3 folder is missing from project unipdf

### ISSUE THREAD

**Issue by nuwaida** [unidoc/unipdf#317]
Hi, 
I'm using git submodule with my go project.
When importing the creator, it refers to v3 folder, and there is no such folder in the unipdf library.
am I missing something here?

I get many errors like this when running the project: 
..\vendor\github.com\unidoc\unipdf\creator\block.go:14:2: cannot find package "github.com/unidoc/unipdf/v3/common" in any of

I have the correct GOPATH, the vendor/github.com/unidoc/unipdf is missing v3 folder and files.

Thanks,
Nazem

**Comment by gunnsth** [comment]
unipdf uses go modules as the primary for loading, via go.mod file.
