### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by RangoW** [unidoc/unipdf#329]
I have run the pdf-sign-appearance and get a successful result. The signature field's appearance is not a custom picture? 
![image](https://user-images.githubusercontent.com/30715970/80454717-107fdb80-895d-11ea-9241-46cbbc8b42f6.png)

**Comment by gunnsth** [comment]
Duplicate of #123 ?

**Comment by RangoW** [comment]
Understander.  I will discuss with my boss about purchasing authorization.
