### ISSUE TITLE
[BUG] Invoice table has rendering problems when there are many items in AddLine/AddTotalLine

### ISSUE THREAD

**Issue by venison** [unidoc/unipdf#339]
## Description
There are two somewhat separate items I noticed while trying out different inputs.  I tested this against the latest from the development branch, (my go.mod shows: github.com/unidoc/unipdf/v3 v3.6.3-0.20200505001727-9ef2f2769408)

- When `invoice.AddLine` has only a few items (say 5) but `invoice.AddTotalLine` has more (say 15), the invoice lines print in the table property, but all of the subtotal/totals are missing.
- When `invoice.Addline` has enough items to force a new page and there are many items in `invoice.AddTotalLine` the next set of content will be bunched up over the totals/subtotals.

## Expected Behavior
When there are long tables it would be great if the content didn't get lost or did not overlap.

## Actual Behavior
1. Using pdf_invoice_advanced.go you can see this by changing the for loop adding lines to 5 or 15 depending on the issue.  In addition, you would want to add a for loop to add a number of total lines using `invoice.AddTotalLine(...`, I did a for loop of 15 and that seemed to be enough.

## Attachments
Include a self-contained reproducible code snippet and PDF file that demonstrates the issue.

[example.zip](https://github.com/unidoc/unipdf/files/4583680/example.zip)

**Comment by venison** [comment]
Also tried with v3.7.0 rather than the dev branch hash.  Seems to still render improperly.

**Comment by gunnsth** [comment]
@venison Addressed by #342 . Can you try again with development branch?

**Comment by venison** [comment]
I tried both cases and they seem to be working for me locally now.  Well done!
