### ISSUE TITLE
[BUG] It is not filling select/choice fields

### ISSUE THREAD

**Issue by rafaelsanzio** [unidoc/unipdf#341]
#297  Description
I am trying to fill a pdf with a select/choice by using pdf_form_fill_json.go , however it is not filling.

I haven't got any error, just a log:
[DEBUG] logging.go:125 Unexpected string for button/choice field. Converting to name: 'RJ'

## Expected Behavior
I expected that the fields were filled with an option selected

## Actual Behavior
I am trying to run a field pdf and got this debug and the field select/choice is not filled

I haven't got any error, just a log:
[DEBUG] logging.go:125 Unexpected string for button/choice field. Converting to name: 'RJ'

## Attachments
[teste.json.txt](https://github.com/unidoc/unipdf/files/4588990/teste.json.txt)
[teste.pdf](https://github.com/unidoc/unipdf/files/4588991/teste.pdf)

**Comment by gunnsth** [comment]
@rafaelsanzio This has been resolved by #370 and is available in development branch. Can you confirm?
