### ISSUE TITLE
[BUG] Table cell text wrap seems to incorrectly calculate a line break and then overlaps the content with the next row.

### ISSUE THREAD

**Issue by venison** [unidoc/unipdf#347]
## Description
It seems to be that when the content in a cell is 13 characters long and contains some kind of punctuation (,.; ) that the cell contents break/wrap on a space into what would be the next row, even if there is enough space.  In addition, the wrapped text is overlapping with the following row.  This was tested against commit #f60e313cdb75 from the development branch.

## Expected Behavior
The content should probably not have wrapped in the first place, there seems to be enough space for it to fit, but if it does need to wrap, it should clear the next row instead of overlapping.

## Attachments
Include a self-contained reproducible code snippet and PDF file that demonstrates the issue.

[tableWrapIssue.zip](https://github.com/unidoc/unipdf/files/4611190/tableWrapIssue.zip)

**Comment by venison** [comment]
ooh, shiny.  Ready for me to verify locally?  :)

**Comment by gunnsth** [comment]
@venison That would be great.  It has been merged into development branch.

**Comment by venison** [comment]
Fixes all the cases I have locally.  Awesome!  Thanks!

**Comment by gunnsth** [comment]
Great!
