### ISSUE TITLE
[BUG] Where to get a license?

### ISSUE THREAD

**Issue by localhosted** [unidoc/unipdf#350]
## Description

How can we get a license if we are using unipdf in an AGPL codebase?

## Expected Behavior

Able to quickly receive a license for open source apps

## Actual Behavior

It's currently hidden and unkown how to get a license. Emails sent to sales that are not inquiring about a paid license aren't responded to.

**Comment by xplodwild** [comment]
The license price is just insane even for companies. We wanted to upgrade our original go-fpdf to this, and instead decided to just keep our legacy projects on the original go-fpdf (which was not hidden paid software like this) and migrate newer ones to wkhtml2pdf. See https://github.com/SebastiaanKlippert/go-wkhtmltopdf
