### ISSUE TITLE
[BUG]Search and replace text would lost table of contents

### ISSUE THREAD

**Issue by xssworm** [unidoc/unipdf#365]
## Description
Can successfully replace text, but will lose the table of contents.

## Expected Behavior
replace the text '取扱説明書' in page 1 use this example:
[https://github.com/unidoc/unipdf-examples/blob/development/text/pdf_search_replace_advanced.go](url)

## Actual Behavior
$ go run pdf_search_replace_advanced.go quietcontrol-30_ja.pdf output.pdf "取扱説明書" "xxxxxx"
Successfully created output.pdf
The text was successfully replaced, but the table of contents was lost, and the text becomes invisible.

**before:**
<img width="860" alt="before" src="https://user-images.githubusercontent.com/2535068/83349107-c4152a80-a364-11ea-95cd-a4c3cabbc299.png">

**after:**
<img width="807" alt="after" src="https://user-images.githubusercontent.com/2535068/83349114-d8f1be00-a364-11ea-83c9-afe8e0b9548e.png">

## Attachments
[quietcontrol-30_ja.pdf](https://github.com/unidoc/unipdf/files/4707432/quietcontrol-30_ja.pdf)

<img width="424" alt="003" src="https://user-images.githubusercontent.com/2535068/83349124-f161d880-a364-11ea-8e93-2739f6ebbc04.png">

**Comment by gunnsth** [comment]
You need to copy the Outlines (which store what you call "Table of contents" or sometimes "Bookmarks") from the original document over.  Outlines are stored separately, need something like:
```
outlineTree := reader.GetOutlineTree()
writer.AddOutlineTree(outlineTree)
```
