### ISSUE TITLE
Support for Type3 fonts

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#37]
Currently text extraction fails on some text using this font type. Need to add support for it to properly work for extraction.

**Comment by gunnsth** [comment]
@peterwilliams97 What is the current status of this in extraction?  Are we able to get any information from Type 3 fonts?

**Comment by linhtto** [comment]
I believe that this should be doable. I've seen this error (type3 fonts are currently not supported) for some PDF that Zotfile (a plugin in zotero) has no trouble extracting. Anything to learn from there?

**Comment by 3ace** [comment]
@gunnsth I think this has been implemented https://github.com/unidoc/unipdf-src/commit/67041341aa0e1a8bdb92cc63fec8db7716412783
