### ISSUE TITLE
[BUG] Improve table rendering speed again

### ISSUE THREAD

**Issue by schooltech** [unidoc/unipdf#378]
last time I open [an issue](https://github.com/unidoc/unipdf/issues/318), and the bug is solved at the version 3.6.2， but when I upgrade to the new version 3.8.0，it renders slowly again and the same test project below.
[pdf_test.zip](https://github.com/unidoc/unipdf/files/4809078/pdf_test.zip)

**Comment by gunnsth** [comment]
@schooltech Thanks for reporting the regression.  A fix has been merged into development branch.
