### ISSUE TITLE
Advanced text extraction on columns, tables, equations

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#38]
To properly extract certain text in PDF, it may be necessary to detect/group lines, identify tables, equations.  This may either be done post-extraction of objects or before, depending on what is easier to implement and gives good results.

Also need to assemble a solid corpus for testing, as well as an API prototyping.  Tabular extraction may need a different approach than equations and possibly a different API.

At this point we are collecting input so that we can define this issue better.

**Comment by Ben-harder** [comment]
Any update on this? I've found that unfortunately table extraction seems to be about 50% correct at the moment

**Comment by gunnsth** [comment]
@Ben-harder Can you post some cases where it falls short?  And also the code you are using.

**Comment by Ben-harder** [comment]
Sure. We're using `v3.9.0` and we're getting the pageText object for each page and then I've iterated through `pageText.Tables()` and drawn out the cell bbox's in blue and their bbox's unioned in red to represent the whole table. You can ignore the green outlines. 

Here's an example of what we want with one of the tables it picked up perfectly:
![table_good_1](https://user-images.githubusercontent.com/31527486/91340374-c254da80-e78c-11ea-99c1-8f1a0b46ab33.png)

And here are some examples of where it either picks up lists and thinks they're tables, or it misses some cells in an actual table:
1.
![table_bad_1](https://user-images.githubusercontent.com/31527486/91340365-c123ad80-e78c-11ea-88d8-ce1f7fbb3a26.png)
2.
![table_bad_2](https://user-images.githubusercontent.com/31527486/91340370-c1bc4400-e78c-11ea-8ebe-5daa56eab2af.png)
3.
![table_bad_3](https://user-images.githubusercontent.com/31527486/91340372-c254da80-e78c-11ea-91ee-5b5612e0512d.png)

It also picked up a few numbered lists as well.

**Comment by Alttaf** [comment]
+1 for this

**Comment by gunnsth** [comment]
@Ben-harder Can you share some PDFs that we can use for testing and include in our QA and automated test suites?

**Comment by Ben-harder** [comment]
Sure I can give you the one from the images
[Speer_Permit.pdf](https://github.com/unidoc/unipdf/files/5132449/Speer_Permit.pdf)
[Speer_Permit_overlay.pdf](https://github.com/unidoc/unipdf/files/5132450/Speer_Permit_overlay.pdf)

**Comment by peterwilliams97** [comment]
Ben, I will investigate this.
I have am working on a few versions of table extraction code that I have not submitted yet. They address most/all of the issues you raise but they make other trade-offs so have been holding them back. 

Some of the things I am working on are:

- Grid line detection fixes a lot of cases
- Sparse table detection can be tricky
- Detecting tables without gridlines requires making some judgments

I will see if I can make a small commit that addresses your specific issues next week.
Have you been using any other PDF table extractors? If so, can you tell me which one does the best job on you files?

**Comment by Ben-harder** [comment]
Hi Peter, thank you that sounds great!

And no, I haven't used any other PDF table extractors.

**Comment by Ben-harder** [comment]
So we actually have used AWS Textract, my bad. The results from it on the same document are attached. It's a JSON file, just had to convert it so GitHub would let me upload it.

[Speer_Permit 18WE0486.CP1_Blowdown vent.txt](https://github.com/unidoc/unipdf/files/5151808/Speer_Permit.18WE0486.CP1_Blowdown.vent.txt)

**Comment by peterwilliams97** [comment]
Thanks. That will give me a benchmark to compare against.

**Comment by Elikrag** [comment]
Following up on the examples @Ben-harder posted. Examples 1 and 2 are fixed from v3.11.1, but the issue with 3 remains. Here's two more examples from the same PDF:

![Screenshot from 2020-10-02 16-42-00](https://user-images.githubusercontent.com/33401582/94977618-6d645c80-04ce-11eb-9c5a-f8a06872c426.png)

![Screenshot from 2020-10-02 16-42-22](https://user-images.githubusercontent.com/33401582/94977625-748b6a80-04ce-11eb-8fba-059bfe602300.png)

Along with Ben's 3rd example still not getting fully picked up:

![ex3](https://user-images.githubusercontent.com/33401582/94977761-14e18f00-04cf-11eb-90db-5ed5b5283998.png)

Seems like table identification improved, but cell identification within a table didn't. Curious if there's any update on this? Thanks!

**Comment by gunnsth** [comment]
Table extractions have been improved in v3.13.0 and you should see much better results with your files.

**Comment by anovik** [comment]
In current version https://github.com/unidoc/unipdf/releases/tag/v3.65.0 detection of tables and lines is done by default. If you need to disable it for some file you should use simple extraction like in the example https://github.com/unidoc/unipdf-examples/blob/master/extract/pdf_simple_extraction.go. 

In case of any problem, feel free to open a new issue.
