### ISSUE TITLE
[BUG] Huge ram usage when splitting a 2.5MB pdf

### ISSUE THREAD

**Issue by Kliton** [unidoc/unipdf#380]
## Description
When i'm going to split a pdf with 166 pages ( 2.5 MB ) into one pdf for each page i'm going to use 8gb of ram.

Is this normal?

## Attachments
<img width="1391" alt="Schermata 2020-06-22 alle 18 26 47" src="https://user-images.githubusercontent.com/10452377/85311634-04744e00-b4b6-11ea-9827-ae206257b4eb.png">

![image](https://user-images.githubusercontent.com/10452377/85311801-41d8db80-b4b6-11ea-8842-2000494e5658.png)

**Comment by gunnsth** [comment]
@Kliton Can you contribute a self-contained repro?  I.e. the code and files needed to reproduce the issue?

**Comment by Kliton** [comment]
@gunnsth Hi, i can't post the pdf used because it contains sensitive data of the company. I can tell you that is a pdf  with a lot of tables.

The code is the same as the split example of this repo.

I have tried my function with 3 different pdfs ( also big, like 20MB ) and i have reached at max 100mb of ram.

The problem is with this particular pdf ( i think that it has a lot of "objects" inside ) like table cells ecc.

**Comment by gunnsth** [comment]
OK. That information is not specific enough, we need something to reproduce and work with. 

Make sure you use `NewPdfReaderLazy` when splitting to avoid loading the entire file into memory, which you probably don't want when splitting out only certain pages.

**Comment by Kliton** [comment]
Yeah i've alread tried with reader lazy.

The main problem is the pdf itself: each page contains like 1800 objects.
I have exported the pdf with acrobe premium as "otpimized" and now it has only 22 object.

There is any way with unipdf to handle this pdf with a large amount of objects?

**Comment by Kliton** [comment]
The problem was in the pdf and not in the lib ( the pdf has 1.8k objects)
