### ISSUE TITLE
[BUG]Fill form by json, but cannot display English and digital charcode

### ISSUE THREAD

**Issue by harddies** [unidoc/unipdf#383]
## Description
We created a Chinese charcode PDF, and it contains forms. we used pdf_form_fill_json.go in [https://github.com/unidoc/unipdf-examples](https://github.com/unidoc/unipdf-examples) to fill the PDF forms, but the filled form PDF cannot display English and digital charcode.

How shall we resolve it? emergency

debug info
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='1'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='1'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='1'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='a'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='s'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='d'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='f'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='a'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='s'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='d'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='f'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune='['
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune=']'
[DEBUG] encoder.go:72 Failed to map rune to charcode. rune=' '

fill.json
[
{
"name": "合同",
"value": "合同11111111asdfasdf[] () （）【】。."
}
]

[test.pdf](https://github.com/unidoc/unipdf/files/4841681/test.pdf)

**Comment by gunnsth** [comment]
@harddies Can you please supply a full code and PDF file example so that the issue can be reproduced?

**Comment by gunnsth** [comment]
Closing as missing minimal code/files to reproduce.  Please check https://github.com/unidoc/unipdf-examples/blob/master/forms/pdf_form_fill_custom_font.go  and other examples for form filling.  Need to make sure a font is used that can display the glyphs needed.
