### ISSUE TITLE
[FEATURE] Page orientation

### ISSUE THREAD

**Issue by mchusovlianov** [unidoc/unipdf#399]
Hey, guys!

Does this library have a way to set page orientation (portrait/landscape)? So far I found only the rotation option but that  isn't  actually the same like the landscape orientation.

**Comment by 3ace** [comment]
for an example of creating a landscape PDF document, you can take a look at this code example

[https://github.com/unidoc/unipdf-examples/blob/master/report/pdf_report_landscape.go](https://github.com/unidoc/unipdf-examples/blob/master/report/pdf_report_landscape.go)

basically what you need to do is set the page size accordingly

```
// Switch the page size constant from the available predefined size for a landscape page
c.SetPageSize(creator.PageSize{creator.PageSizeA4[1], creator.PageSizeA4[0]})
```
