### ISSUE TITLE
[BUG] License links not working in README

### ISSUE THREAD

**Issue by amaurymartiny** [unidoc/unipdf#403]
## Description

The readme links to LICENSE.COMMERCIAL and LICENSE.AGPL, but these are 404.

## Expected Behavior

Correct links to both licenses.

## Actual Behavior

1. Go to README
2. Click on LICENSE.COMMERCIAL or LICENSE.AGPL
3. See error

**Comment by ahall** [comment]
It should read like this one: https://github.com/unidoc/unioffice/blob/master/LICENSE.md. We are fixing this today.

**Comment by ahall** [comment]
Fixed in the latest version
