### ISSUE TITLE
[BUG/Question] Enabling LTV on Signature after using sighandler.NewAdobeX509RSASHA1Custom

### ISSUE THREAD

**Issue by Kunamatata** [unidoc/unipdf#412]
I've looked at the examples inside `unipdf-examples` repository for the timestamp code. 
However, I am wondering if I can create the signature with the handler from this method: 
`handler, err := sighandler.NewAdobeX509RSASHA1Custom(signingCert, func(sig *model.PdfSignature, digest model.Hasher) ([]byte, error)` 

And then still be able to enable LTV on the signature afterwards.

**Comment by Kunamatata** [comment]
The documentation doesn't specify how to add LTV to a signature. I think it would be valuable to know if this feature exists before I buy this license.

**Comment by Kunamatata** [comment]
@gunnsth Knowing if this feature exists would confirm my license purchase

**Comment by gunnsth** [comment]
@Kunamatata The LTV feature is in development.  The process is already very far.  It will be available in October.

**Comment by Kunamatata** [comment]
Thank you for the response @gunnsth closing this for less noise.
