### ISSUE TITLE
[BUG] field partial name (T) not specified

### ISSUE THREAD

**Issue by tangximing** [unidoc/unipdf#425]
## Description
I'm trying to read form from pdf with code below, but ends up with error like this "field partial name (T) not specified"

```
ReadForm(arg *ReadFormArg) (resp string, err error) {
	fd, err := fjson.LoadFromPDFFile(arg.Filename)
	if err != nil {
		return
	}
	if fd == nil {
		return
	}
	resp, err = fd.JSON()
	if err != nil {
		return
	}
	return
}
```

## Expected Behavior
parse the pdf successfully and return form json string

## Attachments
there are two form fields in pdf attachment, and the second one is just copied from the first one. if I replace the second one with created form field not copied, it's ok.

[test2.pdf](https://github.com/unidoc/unipdf/files/5557424/test2.pdf)

**Comment by gunnsth** [comment]
@tangximing We cannot reproduce this.  Can you test this again with newest unipdf and provide a self-contained example with full code and files so that it can be reproduced.
