### ISSUE TITLE
[BUG] creator.Draw causes PDF to warp under certain conditions after update in 3.12.3

### ISSUE THREAD

**Issue by echarrod** [unidoc/unipdf#428]
## Description
After updating from 3.7.0 -> 3.13.0, when a number of conditions are met, the whole PDF becomes warped. From my own investigations it looks like:
when calling creator.Draw on any of the 3 elements I am drawing onto the PDF (attached below)
- with v3.12.3+
- AND writer.SetOptimizer being set
- AND ImageUpperPPI being 200 or less
- AND with a heavy PPI single image on a page (see example attached)
then the PDF becomes warped. If I remove any of those criteria this does not happen

From change notes for 3.12.3, looks like this might be something to do with it?
> Improved speed and memory usage of drawing creator blocks to pages. [USD-8]

## Expected Behavior
Image is optimised, PDF stays the same visually

## Actual Behavior
1) Open the attached project
2) Run go test ./...
3) Inspect the produced PDF in /testdata
4) Change any of the criteria above (e.g. change unidoc version to 3.12.2)
5) Run test again - this is how the PDF should look

Input file:
![image](https://user-images.githubusercontent.com/1381991/100450766-2057cd80-30ae-11eb-8227-c046875d2a86.png)

Output file:
![image](https://user-images.githubusercontent.com/1381991/100468691-d500e780-30cc-11eb-977a-fa78f5e5537f.png)

## Attachments
- Input:
[scanned_pdf_rotation_optimisation_check.pdf](https://github.com/unidoc/unipdf/files/5608791/scanned_pdf_rotation_optimisation_check.pdf)

- Output - 
[scanned_pdf_rotation_optimisation_check_443179483.pdf](https://github.com/unidoc/unipdf/files/5608794/scanned_pdf_rotation_optimisation_check_443179483.pdf)

I will email the code snippet separately

[USD-8]: https://unidoc.atlassian.net/browse/USD-8

**Comment by gunnsth** [comment]
@echarrod Thanks for your well written report.  Your conclusion seems likely.  We will take a look at this.

**Comment by echarrod** [comment]
Can confirm this issue disappears after upgrading to 3.19.0 - https://github.com/unidoc/unipdf/releases/tag/v3.19.0
Thanks
