### ISSUE TITLE
[Question] Any known good charting library

### ISSUE THREAD

**Issue by polderudo** [unidoc/unipdf#431]
We are using unipdf to create some realy nice looking PDF reports. The only thing we are really missing a a nice charting library. There does not seem to be anything good lokking stuff for go out there. 

go-echarts looks realy nice, but there is no way to extract the image (using js internaly)
https://github.com/wcharczuk/go-chart is also good for the stuff it does, but it does not realy include much chart types.
https://github.com/gonum/plot is the library that we use now mostly, because it has plety of different charts.

Except go-echarts they all look very academical and the output is not good for beeing used in real reports.

Do you at unidoc know of a good library out there? Commercial or free

**Comment by polderudo** [comment]
fyi, we have a license

**Comment by gunnsth** [comment]
Hi @polderudo Yes, those are both widely used. Are you not able to style them to your needs?  Would be helpful to get a concrete example if what you are looking for, some examples. So we can look further into this.

**Comment by gunnsth** [comment]
@polderudo We have created our own vectorized graphic library UniChart which can be used for graphs.  We based it on https://github.com/wcharczuk/go-chart but extended for generating vectorized output, and more graph formats.  Would be great to get some feedback on it.

For example of a good example using it with report templates, see:
https://github.com/unidoc/unipdf-examples/tree/master/templates/security-report

**Comment by polderudo** [comment]
Thanks. We will definitly have a look and let you know.
