### ISSUE TITLE
[Question] [Bug?] ExtractPageText does not seem to recognize tables

### ISSUE THREAD

**Issue by venison** [unidoc/unipdf#433]
I have been playing with the extractor package to see if it can help us achieve some work around testing.  I'm using unipdf v3.14.0.  In my code I use creator to generate a new pdf with a simple 2 column table.  I write a styled paragraph to each cell's content, draw the table and write it to disk (or memory), and then I read that generated PDF back using the steps in the table_test.go file.

When I extract just the text, it seems to work fine.  I can see my content/text.  The generated PDF also looks visibly correct.  However, if I use ExtractPageText and then try to use the .Tables() method, the returned array is always empty.  I'll provide the code/generated pdf I'm using to play with the functionality in case I'm doing something wrong to cause this problem.

If I'm making a silly mistake, any help would be much appreciated.  
[extractortest.zip](https://github.com/unidoc/unipdf/files/5736928/extractortest.zip)

**Comment by gunnsth** [comment]
@venison If you look at the table in your PDF, it does not really resemble a table?  Table detection is based on identifying tables, similar to how a person would look at a document and identify tables.  Contents in PDFs are not like HTML, there is no "table" element, but just text, lines etc.  I would suggest that you add some borders to the table etc, and then I expect it would identify it.

**Comment by venison** [comment]
Ah, that makes a lot more sense now, perfect.  Thanks!
