### ISSUE TITLE
Fill image form fields

### ISSUE THREAD

**Issue by localhosted** [unidoc/unipdf#435]
**Is your feature request related to a problem? Please describe.**

You can fill image form fields with Adobe Reader. It is important that the same can be done with unipdf.
After filling the form field, when I try to extract the form fields, I get the error:

> [DEBUG]  logging.go:125 ERROR: Stream length cannot be larger than file size
> Error: invalid stream length, larger than file size

**Describe the solution you'd like**

It should be possible to fill image form fields

**Additional context**
This sample pdf has a image form field that is fillable with Adobe Reader:
[controlled.pdf](https://github.com/unidoc/unipdf/files/5777890/controlled.pdf)

**Comment by fterrag** [comment]
Any updates here? I'm also trying to fill an image field, but can't figure out how. Thanks!

**Comment by gunnsth** [comment]
Please file the issue on our Customer Service Desk portal for quicker turnaround.  This feature is not currently supported but it is something we would look at it and see if we can add in an easy way.

@localhosted Thanks for the file.  I think the debug error message is probably unrelated.  Sometimes PDF files have errors that are autocorrected as we load it.  We will check the file though once we get to this issue.

**Comment by gunnsth** [comment]
This feature is available as of just released UniPDF v3.27.0: Please see the example:
https://github.com/unidoc/unipdf-examples/blob/master/forms/pdf_form_fill_image.go
