### ISSUE TITLE
[BUG] Unexpected output from extractor.ExtractText() in v3.17

### ISSUE THREAD

**Issue by compleatang** [unidoc/unipdf#438]
Upgrading to 3.17 and seeing a regression in one of my tests. 

```
expected: "[end]"
actual  : "\x1c\x04\x03\x12\x1d"
```

The tests reads the last page of a PDF, runs ExtractText() and matches the end of the extracted string. Test passes fine on 3.13, .14, .15, and .16 with no changes other than go.mod.

**Comment by gunnsth** [comment]
@compleatang Please share your test case and files.  Otherwise we cannot reproduce this.

**Comment by compleatang** [comment]
FWIW, 3.18 works fine, as does 3.16, 15, 14, 13, and 12. I'm not sure what happened with 3.17 and haven't had time to isolate out for your my test case from our test suite, but it's all fine with 3.18 so I'm going to close the issue.
