### ISSUE TITLE
[Question] Support for render quality?

### ISSUE THREAD

**Issue by DerrickMartinez** [unidoc/unipdf#439]
Hi, we're thinking about using unipdf to read pdfs (using reader) into memory as images. I understand the default us 72dpi correct? Is it possible to increase it to say 400dpi with config?

Thanks

**Comment by gunnsth** [comment]
@DerrickMartinez Can you clarify regarding the purpose.  Are you using the render package to render those to images?

**Comment by DerrickMartinez** [comment]
@gunnsth correct

**Comment by DerrickMartinez** [comment]
@gunnsth any update?

**Comment by gunnsth** [comment]
Yes this will be a feature in next release which is expected next week.
