### ISSUE TITLE
Add test cases for FlateDecode post-decode prediction

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#44]
Should test:
1. TIFF encoding prediction
2. PNG prediction
- None, Sub, Up, Average, Paeth, Combination

Include cases with 1,3,4 color components.

Can assume BitsPerComponent = 8 for now. Support for more BPC will be included in a separate ticket which will include making tests.

**Comment by anovik** [comment]
Currently both PNG and TIFF prediction tests are implemented, for TIFF see TestFlateTiffPredictor
