### ISSUE TITLE
[BUG] "unsupported encoding parameters" with some PDFs when upgrading to 3.19.0+ 

### ISSUE THREAD

**Issue by echarrod** [unidoc/unipdf#446]
## Description
When setting the optimizer on the PdfWriter with:
```go
// Set optimizer.
writer.SetOptimizer(optimize.New(optimize.Options{
	CombineDuplicateDirectObjects:   true,
	CombineIdenticalIndirectObjects: true,
	CombineDuplicateStreams:         true,
	CompressStreams:                 false,
	UseObjectStreams:                true,
	ImageQuality:                    80,
	ImageUpperPPI:                   100,
}))
```
When a subsequent call to write with this writer is made with:
```go
err = writer.Write(outputFile)
```
The error "unsupported encoding parameters" is thrown.

This was introduced in 3.19.0+, these PDFs work fine with versions before this.

## Expected Behavior
- The writing to succeed

## Actual Behavior
1) Open the attached project
2) Run go test ./...
3) Inspect the produced PDF in /testdata

## Attachments
- I will send the project separately.

**Comment by Alttaf** [comment]
+1

**Comment by gunnsth** [comment]
Fixed in newest release https://github.com/unidoc/unipdf/releases/tag/v3.27.0
