### ISSUE TITLE
The Image size is altering when trying to Print 300 DPI in PDF

### ISSUE THREAD

**Issue by Mahendershah** [unidoc/unipdf#449]
## Description
We have a image that is fixed size and is in 300 DPI. We want to add that image in the PDF. On doing so when we add the image in the PDF using Unidoc unipdf, the image overall size is reducing.

## Expected Behavior
Since the size of the image and DPI is fixed i.e. DPI is 300 the size of the image in the output PDF should be of the same size as provided

## Actual Behavior

**********************************************************************
pageSize := creator.PageSize{creator.PageSizeA4[0], creator.PageSizeA4[1]}
	c.SetPageSize(pageSize)
	c.NewPage()
	img, err := getImage(c, imgPath, 22.2, 18.8, 80.35)
	_ = c.Draw(img)
c.SetOptimizer(optimize.New(optimize.Options{
		**ImageQuality:  300,
		ImageUpperPPI: 300,**
	}))

	err = c.WriteToFile(outputPath)

The above bold text shows how we are specifying the Optimizer to create 300 DPI image.
*************************************************
func getImage(c *creator.Creator, imgPath string, x float64, y float64, w float64) (*creator.Image, error) {
	img, err := c.NewImageFromFile(imgPath)
	if err != nil {
		common.Log.Debug("Error loading image: %v", err)
		return nil, err
	}

	//var xx = float64(300 * 1.0 / 25.4)
	new_x := x * creator.PPMM
	new_y := y * creator.PPMM
	new_w := w * creator.PPMM
	img.ScaleToWidth(new_w)
	img.SetPos(new_x, new_y)
	return img, nil
}

## Attachments
None

**Comment by Mahendershah** [comment]
I am working for a company and we are having the license for use in commercial product.

**Comment by gunnsth** [comment]
Hi @Mahendershah I do not recall seeing this reported in our service desk?  Was it filed there, and has this been resolved?  Would be good to close.
There was a fix related to image optimization with PPI settings in the newest release https://github.com/unidoc/unipdf/releases/tag/v3.27.0

**Comment by sampila** [comment]
Hi @Mahendershah, we closing this issue for now and you can re-open if the still is still not resolved after update the unipdf into latest version.
