### ISSUE TITLE
[BUG]`nil pointer dereference` when `EnableFontSubsetting` un unused compositeFont

### ISSUE THREAD

**Issue by sify21** [unidoc/unipdf#451]
## Description
When `EnableFontSubsetting` un unused compositeFont, the program panics with a nil pointer dereference, which causes the program shutdown. 

## Expected Behavior
ignore an enabled font that is not used

## Actual Behavior
1. create multiple fonts with  `model.NewCompositePdfFontFromTTF`
2. enable them with `(*Creator).EnableFontSubsetting`
3. use one of the fonts, but not all of them

**Comment by gunnsth** [comment]
@sify21 Thanks for submitting the problem.  Can you please attach all the files and code needed to reproduce the case?

**Comment by sify21** [comment]
@gunnsth It's [here](https://github.com/sify21/testunipdf)

**Comment by 3ace** [comment]
@sify21 This issue should be fixed on the latest UniPDF v3.22.0

**Comment by sify21** [comment]
Confirm it's fixed
