### ISSUE TITLE
Please consider adding the word 'commercial' in description

### ISSUE THREAD

**Issue by IGLOU-EU** [unidoc/unipdf#456]
Please consider adding the word 'commercial' in your 'about' and README description.
![scr_163723](https://user-images.githubusercontent.com/15379333/116817170-66d1bc80-ab65-11eb-9fd0-4945f351c0c0.png)

**This is an OpenSourceSoftware not a FreeSoftware. And the license file is ... to understand.**

---
I wanted to use your library for an order (I'm freelance), unfortunately I noticed that it was a commercial software only after I finished my code (my PDF reader does not display your red line). 

---
I wanted to buy a license (no problem with that), but for a small job at 2k euro ... it's REALLY too expensive.

**Comment by ahall** [comment]
Hi @IGLOU-EU there is a free tier for up to 100 documents per month in our pay as you grow model. Just register at https://cloud.unidoc.io/. There is a simple phone home functionality that sends us only how many documents you have processed to keep track of the document credits. Contact us at sales@unidoc.io if you are interested and we can send you more prices. We have a few pricing models to try to cater to more users, hope this helps!

**Comment by IGLOU-EU** [comment]
It is a commercial offer, with a proprietary license. Your description is not transparent @ahall

**Comment by sistoi** [comment]
not really cool how this got swept under the carpet

**Comment by gatspy** [comment]
Trickery!
