### ISSUE TITLE
[BUG] Styled paragraph text can overlap when using different font sizes

### ISSUE THREAD

**Issue by pfouilloux** [unidoc/unipdf#462]
## Description
Styled paragraph containing text chunks with different font sizes and newlines can cause text to overlap.

## Expected Behavior
No overlap. Ex:
![image](https://user-images.githubusercontent.com/7494211/125028598-ab308a00-e0cb-11eb-82e3-606a7dd242fc.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/7494211/125028657-c7342b80-e0cb-11eb-96c9-b8f756d1c1d1.png)

## Attachments
Please see code on the playground: https://play.unidoc.io/p/b292aee252a6e90

**Comment by pfouilloux** [comment]
> Welcome! Thanks for posting your first issue. The way things work here is that while customer issues are prioritized, other issues go into our backlog where they are assessed and fitted into the roadmap when suitable. If you need to get this done, consider buying a license which also enables you to use it in your commercial products. More information can be found on https://unidoc.io/
Hi! Regarding☝️ 
We are a customer, happy to submit this issue through other channels if that makes things easier to prioritize 🙂

**Comment by gunnsth** [comment]
Thanks for the report.  The work on a fix is in progress.

**Comment by gunnsth** [comment]
Fixed in v3.27.0
