### ISSUE TITLE
[BUG] Images are rendered with low quality

### ISSUE THREAD

**Issue by zgordan-vv** [unidoc/unipdf#469]
## Description
I am trying to render an image from the PDF document.

## Expected Behavior
The image should look like the PDF document.

## Actual Behavior
The image looks like a very pixelized/blurred version of the PDF document.
1. Copy the attached PDF file in the same directory with the attached code
2. Run the code
3. See error

## Attachments
[chart.pdf](https://github.com/unidoc/unipdf/files/7006676/chart.pdf)
[chart.png](https://user-images.githubusercontent.com/8694210/129887607-57bb7849-a701-4dcd-81f6-d4278bbf9c47.png)
```
package main

import (
    "os"
    "github.com/unidoc/unipdf/v3/model"
    "github.com/unidoc/unipdf/v3/render"
)

func main() {
    f, err := os.Open("chart.pdf")
    if err != nil {
        panic(err)
    }
    defer f.Close()

    reader, err := model.NewPdfReaderLazy(f)
    if err != nil {
        panic(err)
    }
    chartPage, err := reader.GetPage(1)
    if err != nil {
        panic(err)
    }

    if err = render.NewImageDevice().RenderToPath(chartPage, "chart.png"); err != nil {
        panic(err)
    }
}
```

**Comment by gunnsth** [comment]
Basically just need to set the returned (from render.NewImageDevice()) `device.OutputWidth = width` to the desired pixel output width.
