### ISSUE TITLE
[FEATURE] PdfPage.Rotate value always nil

### ISSUE THREAD

**Issue by DerrickMartinez** [unidoc/unipdf#471]
Not sure if this is a bug or a feature... Renaming to feature.

## Description
Page rotate value is always Nil if Rotate flag is missing

## Expected Behavior
Grab a PDF that's rotated that is missing the Rotate field. If there is no /Rotate field it should calculate the transformation off cm values. But instead it is nil so I think that code must be missing

**Comment by gunnsth** [comment]
This can happen if the rotation is inherited.  To get the effective value, use
```
// GetRotate gets the inheritable rotate value, either from the page
// or a higher up page/pages struct.
func (p *PdfPage) GetRotate() (int64, error) {
```
