### ISSUE TITLE
[QUESTION] error: Credits exceeded

### ISSUE THREAD

**Issue by strivefatup** [unidoc/unipdf#479]
I got an error extracting the text content from the pdf file 
[Copy the sample code, read the file error](https://github.com/unidoc/unipdf-examples/blob/master/extract/pdf_extract_text.go)
The error occurred on line 51 
[pdf file](http://www.gov.cn/zhengce/pdfFile/2021_PDF.pdf)
Is it because of the Chinese problem? Or the file is too big

**Comment by gunnsth** [comment]
Hi @strivefatup Seems like you ran out of the free monthly document credits, 100/month ?
