### ISSUE TITLE
[BUG]pdf to png font render error

### ISSUE THREAD

**Issue by YuiFn** [unidoc/unipdf#486]
## Description
Font rendering error when rendering pdf with imageDevice

```go
   target := "taiwen.pdf"
	now := time.Now()
	reader, f, err := model.NewPdfReaderFromFile(target, nil)
	if err != nil {
		log.Fatalf("Could not create reader: %v\n", err)
	}
	defer f.Close()
	numPages, err := reader.GetNumPages()
	if err != nil {
		log.Fatalf("Could not retrieve number of pages: %v\n", err)
	}
	basename := strings.TrimSuffix(filepath.Base(target), filepath.Ext(target))
	device := render.NewImageDevice()
	device.OutputWidth = 800
	for i := 1; i <= numPages; i++ {
		page, err := reader.GetPage(i)
		if err != nil {
			log.Fatalf("Could not retrieve page: %v\n", err)
		}
		outFilename := fmt.Sprintf("%s_%d.png", basename, i)
		if err = device.RenderToPath(page, outFilename); err != nil {
			log.Fatalf("Image rendering error: %v\n", err)
		}
	}
```

## Expected Behavior
all rendering ok

## Actual Behavior
use [pdf_image_render](https://github.com/unidoc/unipdf-examples/blob/master/render/pdf_image_render.go)， see output

## Attachments
Include a 
[AL951611050249.pdf](https://github.com/unidoc/unipdf/files/8358993/AL951611050249.pdf)
![AL951611050249_1](https://user-images.githubusercontent.com/38058823/160311038-836d027a-56cc-47aa-8038-a75d2af380f0.png)
[taiwen.pdf](https://github.com/unidoc/unipdf/files/8358994/taiwen.pdf)
![taiwen_1](https://user-images.githubusercontent.com/38058823/160311046-6e4f9f10-55ce-4286-a5d0-0b0a081dd8e8.png)
self-contained reproducible code snippet and PDF file that demonstrates the issue.

**Comment by 0x-1** [comment]
same. seems to be a problem with the render. my blind guess would be fonts.
![image](https://github.com/unidoc/unipdf/assets/102146/01ae3a9f-65c9-465b-ba71-81421ab2cb02)

**Comment by sampila** [comment]
Hi @YuiFn, @zacharysyoung and @0x-1 

We release new UniPDF version to improve font rendering https://github.com/unidoc/unipdf/releases/tag/v3.52.0,

You can try and would be good if you can confirm if the issue is resolved by latest version of UniPDF.

Thanks

**Comment by zacharysyoung** [comment]
@sampila, yes, 3.52.0 fixed it, thank you.

Cheers!

**Comment by YuiFn** [comment]
@sampila thank you. this work
