### ISSUE TITLE
[FEATURE] support pdf printing

### ISSUE THREAD

**Issue by UDBIAWDIF** [unidoc/unipdf#487]
Hi !

Do you have plan to support pdf printing?

**Comment by gunnsth** [comment]
@UDBIAWDIF Can you clarify what you mean by pdf printing?  We do have PDF rendering to image capability.

**Comment by UDBIAWDIF** [comment]
> @UDBIAWDIF Can you clarify what you mean by pdf printing? We do have PDF rendering to image capability.

I just want to directly printing pdf, but I can live with that.

**Comment by gunnsth** [comment]
OK.  Examples of this can be found in https://github.com/unidoc/unipdf-examples/tree/master/render
