### ISSUE TITLE
[FEATURE] Ability to set opacity on styledParagraph

### ISSUE THREAD

**Issue by soapiestwaffles** [unidoc/unipdf#505]
We have a use case where we require to write text over the top of existing text, but, we need this new text to not be fully opaque. Is there any way currently, that maybe I'm just not seeing in the docs, to set opacity on a StyledParagraph similar to how you can set opacity on a drawn line?

**Comment by sampila** [comment]
Hi @soapiestwaffles,
The `StyledParagraph` works different compared to the graphic elements.
Could you explain your use case and probably give us your desired PDF results with text opacity, so we can understand and try to create example that match your use case.

Best regards,
Alip

**Comment by soapiestwaffles** [comment]
I was pretty sure this was the case, but thought I would make a feature request and see. 

The use-case would be adding semi-transparent text over the top of another block of text. I.e. "DRAFT" over a small paragraph or something. 

I suppose I could always do a workaround of rendering the text to an image and then using transparency on the image. If you have a better way to do it, though, I would definitely love to hear it!

**Comment by sampila** [comment]
If your use case is adding a `DRAFT` text like watermark into PDF page, probably you can try this example: https://github.com/unidoc/unipdf-examples/blob/aad607a68160971dacc06a37b88568b64625b8be/image/pdf_watermark_image.go

**Comment by soapiestwaffles** [comment]
yeah, I'll just rasterize whatever text the user inputs to an image and then use it like in that example. That will work. Thank you :)

**Comment by sampila** [comment]
You are welcome, glad to hear that :)
