### ISSUE TITLE
[BUG] Signature is not compliant with the ETSI standard (PAdES)

### ISSUE THREAD

**Issue by acha-bill** [unidoc/unipdf#507]
## Description

I have a document that contains 1 signature from [skribble.com](https://www.skribble.com/). When I add a signature to it, Adobe Acrobat says it's valid and all checks are green. However, [validator.ch](https://www.validator.admin.ch/) says it has been modified and an annotation has been added.

Report from validator.ch:

> The signature application that applied the second signature did not do so in compliance with the ETSI standard. Because at least one hash value of a signed data object included in the signing process does not match the corresponding hash value in the signature.
> 
> Here is an excerpt from the XML report:
> 
> <ns5:ValidationStatus>
> <ns2:MainIndication>urn:etsi:019102:mainindication:failed</ns2:MainIndication>
> <ns2:SubIndication>urn:etsi:019102:subindication:HASH_FAILURE</ns2:SubIndication>
> </ns5:ValidationStatus>
> 

These issues are not present in the initial document.
I'm using a custom handler to sign (If it matters)

## Expected Behavior
The signatures should be PAdES compliant

## Attachments
Signatures are valid according to Acrobat Reader
![Screenshot 2023-01-13 at 14 51 09](https://user-images.githubusercontent.com/57879913/212335533-d973a5f8-197e-47b2-82ec-d32986e0d8b6.png)

Initial document:  [input.pdf](https://github.com/unidoc/unipdf/files/10412294/input.pdf)
Signed document [document.pdf](https://github.com/unidoc/unipdf/files/10412060/document.pdf)

The 2nd signature is invalid according to [validator.ch](https://www.validator.admin.ch/)
![Screenshot 2023-01-13 at 14 53 35](https://user-images.githubusercontent.com/57879913/212335925-8e43c20c-b0f0-4fbf-bc64-425ee9c9a589.png)

Full report: [Report_doc_eGov_SigVal.pdf](https://github.com/unidoc/unipdf/files/10412072/Report_doc_eGov_SigVal.pdf)

**Comment by sampila** [comment]
Hi @acha-bill,

Thank you for reporting this issue, we will check and get back to you.

**Comment by acha-bill** [comment]
Hi @sampila ,

Any update on this?

**Comment by sampila** [comment]
Hi @acha-bill,

Currently the ETSI PAdES signature handler are in our roadmap.
We are trying to implement the ETSI PAdES standard into our signature handler.
We will give an update if this has been implemented and passed our QA.

**Comment by acha-bill** [comment]
Thanks

**Comment by felixhaegele** [comment]
Hi Sampila, what's the rough timeline on the ETSI PAdES standard?
We have customers and prospects asking for this and need to be able to answer.
Best, Felix

**Comment by stephalba** [comment]
Hi @sampila 

Could you please provide an update on this?

**Comment by sampila** [comment]
Hi @felixhaegele, @stephalba and @acha-bill 

We released new UniPDF version https://github.com/unidoc/unipdf/releases/tag/v3.50.0 to support the PAdES signature, starting v3.49.0 it is already support the PAdES Baseline B.

We closing this issue now and feel free to re-open the ticket if you still have issue regarding this.

Thanks.
