### ISSUE TITLE
[BUG] Does not work without the Internet

### ISSUE THREAD

**Issue by probonopd** [unidoc/unipdf#510]
## Description
I need to use the software on a system that is not connected to the Internet.

## Expected Behavior
It works.

## Actual Behavior
`panic: Post "https://cloud.unidoc.io/api/metered/status": dial tcp: lookup cloud.unidoc.io: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.`

**Comment by sampila** [comment]
Hi @probonopd, 

The metered license requires internet connection to works, you need offline license for system that not using internet connection.

License information:

> UniPDF requires license codes to operate, there are two options:
> 
> Metered License API keys: Free ones can be obtained at https://cloud.unidoc.io/
> Offline Perpetual codes: Can be purchased at https://unidoc.io/pricing

Best regards,
Alip

**Comment by probonopd** [comment]
Never seen such things in open source projects on GitHub. Really surprised!
