### ISSUE TITLE
[FEATURE] Need a way to specify position of a word

### ISSUE THREAD

**Issue by sagar-kalburgi-ripcord** [unidoc/unipdf#518]
**Is your feature request related to a problem? Please describe.**
I am trying to utilize the JSON response from Google Vision OCR API to create a searchable PDF. The JSON response consists of the details of the text layout. I used the unipdf Go library to add the image of a scanned text document to a PDF file, and then tried to overlay the text contained in the JSON response on top of it. Unipdf Go library does provide a way to specify the position of a paragraph, but it does not provide a way to specify the position of each word as specified in the text layout. There is [this](https://apidocs.unidoc.io/unipdf/v3.39.0/github.com/unidoc/unipdf/v3/creator/#StyledParagraph.Insert) function but it does not allow to specify the coordinates of the word (text chunk).

**Describe the solution you'd like**
Library function to specify the position of a word

**Describe alternatives you've considered**
I did try to consider each word as a paragraph to position it via coordinates using the function https://apidocs.unidoc.io/unipdf/v3.39.0/github.com/unidoc/unipdf/v3/creator/#StyledParagraph.SetPos 
but its not getting rendered properly, moreover it is semantically wrong.

**Comment by sampila** [comment]
Hi @sagar-kalburgi-ripcord,

Could you share runnable code snippet for us to reproduce the issue on our end?

Best regards,
Alip

**Comment by sampila** [comment]
Hi @sagar-kalburgi-ripcord, 

Since no response yet, we closing this issue for now.

You can re-open the issue and share us the code snippet, so we can assist you.
