### ISSUE TITLE
[FEATURE] Add more presets and initializer for PageSize

### ISSUE THREAD

**Issue by Shion1305** [unidoc/unipdf#535]
I suggest these 2 points. (Sorry for my poor English.)
- Adding more presets for PageSize
- Adding Initializer for PageSize, like NewPageSizeMM(width int, height int)

Currently, the following preset of PageSize are available.
- PageSizeA5
- PageSizeA4
- PageSizeA3
- PageSizeLegal
- PageSizeLetter
Adding more presets would be useful for users like me.
I suggest adding the following presets.
- ISO/JIS B5, B4,B3
- Business Card Sizes (JIS: 91mmx55mm, US Standard: 3.5inchx2inch)

Also, I suggest adding an initializer for PageSize.
Currently, there are no initializers available for PageSize,
it is a kind of confusing figuring out how to use custom PageSize.
Adding an initializer would provide library users with some level of convenience.

**Comment by sampila** [comment]
Hi @shion1305,

Thanks for the suggestions, we will considering your feedback. 
Currently to sets the custom page size should be easy, like if you want to set the page size to US Standard: 3.5inchx2inch, you can follow this line of code below
```
c := creator.New()

...
pageSizeUSStrandard := creator.PageSize{3.5 * creator.PPI, 2 * creator.PPI}

c.SetPageSize(pageSizeUSStrandard)
```

Our API references can be seen on https://apidocs.unidoc.io/unipdf/v3.39.0

Best regards,
Alip
