### ISSUE TITLE
[BUG] incorrect object position when draw svg graphics

### ISSUE THREAD

**Issue by dhalkin** [unidoc/unipdf#540]
## Description
Svg graphics object has  incorrect position on result pdf file. Problem reproduced after v3.51.0 versions
## Expected Behavior
Drawing svg object in properly coordinates

## Actual Behavior
The SVG object is drawn with an offset

## Attachments
Image and svg graphics has the same coordinates but drawn in different position.
<img width="1023" alt="Screenshot 2023-12-05 at 18 53 36" src="https://github.com/unidoc/unipdf/assets/5365758/c99a31a7-b25a-4920-adda-4ac1c8b5b8b9">
[hello_world.pdf](https://github.com/unidoc/unipdf/files/13564214/hello_world.pdf)

**Comment by dhalkin** [comment]
Hello @sampila, here is it.

![stamp](https://github.com/unidoc/unipdf/assets/5365758/852e136f-e5eb-4425-bd07-065c35e8b74a)

**Comment by sampila** [comment]
> Hello @sampila, here is it.
> 
> ![stamp](https://private-user-images.githubusercontent.com/5365758/289068852-852e136f-e5eb-4425-bd07-065c35e8b74a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTE3MzQsIm5iZiI6MTcwMjgxMTQzNCwicGF0aCI6Ii81MzY1NzU4LzI4OTA2ODg1Mi04NTJlMTM2Zi1lNWViLTQ0MjUtYmQwNy0wNjVjMzVlOGI3NGEuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTdUMTExMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ2MWM0NjIxMTM2YjQ2NGRlMjliNTJjYjIzZTg5ZTg2NjE2OWQ3ZTk5MWM5OTczZTczYWZkN2E0NDkzYWM3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y0ffh3MOX9O60bi8oH59V-sR7xbNVVsbLW7LdCTO4kM)

Thanks for sharing the SVG file, currently we are investigating this issue.

**Comment by sampila** [comment]
Hi @dhalkin,

We released new UniPDF version v3.53.0 https://github.com/unidoc/unipdf/releases/tag/v3.53.0 to solve this issue.

We closing this issue for now and you re-open the issue if this issue still not resolved after updating UniPDF to the latest version.

Best regards,
UniDoc team.

**Comment by sampila** [comment]
Hi @dhalkin,

We apologize, the fix for this issue will be released on the next release, not included in v3.53.0.

We re-open the issue for now.
