### ISSUE TITLE
Render method produces poor quality images.

### ISSUE THREAD

**Issue by danvergara** [unidoc/unipdf#543]
## Description
`Render` method from `render` package only produces poor quality images. The images sees blurry and seems the images' size is fixed to 612 × 792 pixels.

## Expected Behavior
Higher quality images out pdf pages.

## Actual Behavior
I've been consuming the unipdf package as a library, but the easiest way to reproduce this is running the [cli](https://github.com/unidoc/unipdf-cli).

`unipdf render -o images.zip in_file.pdf
`
I got the exact same result.

## Attachments

I'm attaching the Bitcoin Whitepaper because that was the pdf file I was testing against and the first one that came to my mind that is free to download.

`unipdf render -o bitcoin.zip bitcoin.pdf `

[bitcoin.pdf](https://github.com/unidoc/unipdf/files/14000034/bitcoin.pdf)

**Comment by 3ace** [comment]
@danvergara you could set the image width by doing it like this:

```golang
device := render.NewImageDevice()
device.OutputWidth = 2048
```

this is the image example of that

![bitcoin_1](https://github.com/unidoc/unipdf/assets/509131/d215f08e-2519-430c-9e86-220aa0f2edf7)

**Comment by danvergara** [comment]
@3ace  That worked for met!

Thanks!
