### ISSUE TITLE
[BUG] no matching font found in the system

### ISSUE THREAD

**Issue by sagar-kalburgi-ripcord** [unidoc/unipdf#547]
## Description
When I use unipdf in a debian docker container to merge several PDF files, I get an error _no matching font found in the system_

But when I run the same logic locally on my Macbook I do not get this error.

## Expected Behavior
Unipdf should not throw such error or need a way to mitigate the error. Do we need to install fonts in the Dockerfile? If so how do we do that?

## Actual Behavior
Unable to specify steps to reproduce because it is only reproducible in a Kubernetes environment using our proprietary code.

**Comment by sagar-kalburgi-ripcord** [comment]
To be more specific, the error is returned by a call to `pdfWriter.Write()`

**Comment by 3ace** [comment]
@sagar-kalburgi-ripcord on linux environment, you could try adding some fonts in one of the following folders:

- `~/.fonts`
- `~/.local/share/fonts`
- `"/usr/local/share/applications`
- `"/usr/share/applications`

**Comment by sagar-kalburgi-ripcord** [comment]
Hi @3ace thanks, I did install some fonts and the issue seems to be resolved now
