### ISSUE TITLE
[BUG] miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [unidoc/unipdf#555]
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9243197843/job/25427030599 

```
====================================================================================================
append to slice `_gcgeg` with non-zero initialized length at https://github.com/unidoc/unipdf/blob/master/model/model.go#L4714:1[9](https://github.com/alingse/go-linter-runner/actions/runs/9243197843/job/25427030599#step:4:10)2
====================================================================================================
```

the `_gcgeg :=make ([]string ,len (_ebebe ._cbag .Keys ()))` should be `_gcgeg :=make ([]string , 0,len (_ebebe ._cbag .Keys ()))`

**Comment by kellemNegasi** [comment]
Not related to UniPDF.
