### ISSUE TITLE
Digital Certificate : To add Digital signature on a PDF

### ISSUE THREAD

**Issue by BhanuuPrakash** [unidoc/unipdf#561]
Hello UniDoc Team,

We are currently integrating digital signatures into our PDF documents using UniPdf and need guidance on obtaining a digital certificate. Our goal is to ensure that the attached digital certificate can be validated by the end users for authenticity and security.

Specifically, we are looking for recommendations on:
A Certificate Authority (CA) that provides digital certificates suitable for document signing.

Thank you for your assistance!

**Comment by sampila** [comment]
Hi @BhanuuPrakash 

About Certificate Authority (CA), as recommended by adobe, here the list:
https://helpx.adobe.com/acrobat/kb/approved-trust-list1.html

As we had partnership with GlobalSign, we added sdk also if you happened to use the GlobalSign example can seen here https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_external_globalsign.go
