### ISSUE TITLE
Unidoc 3.61.0 gives expired key error when using valid key

### ISSUE THREAD

**Issue by JoeEdwards-GloveBox** [unidoc/unipdf#564]
Sorry if this isn't the normal avenue for addressing such issues, but we have a production issue affecting our customers and so far `support@unidoc.io` has been unresponsive.

We are a paying customer that seems to have an expired key.  We receive the following error when trying to use unidoc: `"unable to load unidoc license key: invalid license: The license has already expired.\nYou may need to update the license key to the newest license key for your organization.\nTo find your newest license key, go to https://cloud.unidoc.io and go to the license menu."`

Trying to log into our account to fix the issue, via `https://cloud.unidoc.io/login`, we the following error message is displayed in the UI: `Please activate your account first.  Inactive User`

Our key and account have been working up until a few days ago from what I can tell.

Please let us know how we can correct our account and key.  Feel free to reach out directly via my email `joe@gloveboxapp.com` and close the issue if you wish to take this discussion to a different venue.

EDIT:
We have confirmed that we are using a correct key.  The issue seems to be limited to when we are using the latest `3.61.0` version.  Using the same key with `3.55.0` seems to work fine.

**Comment by JoeEdwards-GloveBox** [comment]
I have updated the title and summary of this issue to reflect our latest research into this issue.

Here is a little test script which you can use to test the bug:
```
package bug_test

import (
	"fmt"
	"testing"

	"github.com/unidoc/unipdf/v3/common/license"
)

// Example of an offline perpetual license key.
const offlineLicenseKey = `<LICENSE KEY>`

func init() {
	customerName := `<CUSTOMER NAME>`

	ofk := fmt.Sprintf("-----BEGIN UNIDOC LICENSE KEY-----\n%s\n-----END UNIDOC LICENSE KEY-----", offlineLicenseKey)

	err := license.SetLicenseKey(ofk, customerName)
	if err != nil {
		panic(err)
	}
}

func TestFunc(t *testing.T) {
	lk := license.GetLicenseKey()
	if lk == nil {
		fmt.Printf("Failed retrieving license key")
		return
	}
	fmt.Printf("License: %s\n", lk.ToString())

	if 1 == 2 {
		t.Fail()
	}
}

```

**Comment by ipod4g** [comment]
@JoeEdwards-GloveBox We tested your script using two different versions, and it's working well, confirming that the license is valid. If you encounter any issues with your license, please reach out to us through the customer portal, and we'll resolve it for you.
 https://unidoc.atlassian.net/servicedesk/customer/portal/8

**Comment by JoeEdwards-GloveBox** [comment]
@ipod4g I've added the engineer who was experiencing this error on the support thread to help him narrow down the specific issue and why he's receiving the expired key message only when using this version of unidoc.

**Comment by ipod4g** [comment]
@JoeEdwards-GloveBox 
Hello
I’ve checked our internal system, and it looks like we’ve resolved the issue with the expired key. 
I believe we can close this issue now.
If you need any further support or assistance in the future, feel free to open a ticket through our customer portal or create one here.
