### ISSUE TITLE
[BUG] GetAttachedFiles causes panic

### ISSUE THREAD

**Issue by crashingfish** [unidoc/unipdf#565]
## Description
GetAttachedFiles was introduced in 3.5. Calling it on a pdf file with attachment consistently causes panic.

## Expected Behavior
Return a list of attachments if any.

## Actual Behavior
1. Read a pdf file with attachments
2. Call GetAttachedFiles to test.

## Sample code
`	
fileBytes, _ := os.ReadFile(filename)

pdfReader, err := model.NewPdfReader(bytes.NewReader(fileBytes))

attachments, err := pdfReader.GetAttachedFiles()
`

## Attachments
Cannot share internal pdf file due to compliance issues. However the code was testing against loads of files and the issue is consistent.

**Comment by 3ace** [comment]
@crashingfish thank you for the report. We'll investigate this immediately.

**Comment by crashingfish** [comment]
@3ace I missed to share this. Hope this helps.

[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x102e97340]

goroutine 1 [running]:
github.com/unidoc/unipdf/v3/model.(*PdfReader).GetAttachedFiles(0x140004cdce8?)
        /go/pkg/mod/github.com/unidoc/unipdf/v3@v3.57.0/model/model.go:3095 +0x1d0

**Comment by 3ace** [comment]
@crashingfish I've already located the issue and has implement a fix for this. The fix is currently in review internally and hopefully it would be available with our next UniPDF release.

**Comment by crashingfish** [comment]
Thanks much.

**Comment by 3ace** [comment]
@crashingfish we've released new UniPDF version 3.62.0 that should contain a fix for this issue https://github.com/unidoc/unipdf/tree/v3.62.0.

Please test it and let us know the result.

**Comment by 3ace** [comment]
@crashingfish As we haven't received any further updates from you, we are closing this ticket for now. If you experience any additional issues, please open a new ticket. Thank you!
