### ISSUE TITLE
[BUG] Unable to convert pdf images to grayscale "invalidBitsPerComponent"

### ISSUE THREAD

**Issue by rcorry** [unidoc/unipdf#570]
## Description
Following this [example](https://unidoc.io/unipdf-examples/pdf-to-grayscale/) from the documentation, an xobject is failing to convert to an image due to an invalid number of bits per component, in this case the error says there are 4. When printing out the value of the ximg.BitsPerComponent I can see the value is actually 8. This results in an error and the pdf is not converted to grayscale.

## Expected Behavior
The xobject should be converted to an image and subsequently converted to grayscale before being added back to the pdf.

## Actual Behavior
1. Run this [example](https://unidoc.io/unipdf-examples/pdf-to-grayscale/) code
3. Convert the attached file, passing it in as the first argument

## Attachments
[test.pdf](https://github.com/user-attachments/files/17440755/test.pdf)

**Comment by 3ace** [comment]
@rcorry Thank you for contacting us about this issue. We'll take a look at it and update you later if we have more info about this.

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ipod4g** [comment]
@rcorry  I am closing this issue. You can review our solution, and if you continue to experience any problems, feel free to open a new issue here.
