### ISSUE TITLE
Load error: EOF marker not found

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#64]
Errors were  found in a small set of files in a large PDF corpus that are related to not finding the EOF marker of the file. Sometimes the text appears to be just "EO".  Ghostscript processes those files fine.  Example error:
```
[DEBUG]  parser.go:1178 Warning: EOF marker not found! - continue seeking
%"RACE]  parser.go:1168 Looking for EOF marker: "%PDF-1.4
[DEBUG]  parser.go:1178 Warning: EOF marker not found! - continue seeking
[DEBUG]  parser.go:1182 Error: EOF marker was not found.
[DEBUG]  parser.go:1220 Failed seek to eof marker: EOF not found
[DEBUG]  parser.go:1644 ERROR: Failed to load xref table! EOF not found
[DEBUG]  pdf_passthrough_bench.go:282 Reader create error EOF not found

/tmp/eof-marker-not-found/180546.pdf - fail EOF not found
```
This particular file ends with: "%%EO"   A fix involving making the F optional might be enough.

Attachments: Sample of failing files.
[eof-marker-not-found.zip](https://github.com/unidoc/unidoc/files/3127292/eof-marker-not-found.zip)

**Comment by lporras** [comment]
@gunnsth I'm getting this errors with some excels files.  Do you know if there is a way to fix this problem?

**Comment by gunnsth** [comment]
@lporras Excel files?  This is a PDF library, perhaps you should try our Office library to open an Excel xlsx spreadsheet? :).  See for example https://github.com/unidoc/unioffice-examples/tree/master/spreadsheet/text_extraction
