### ISSUE TITLE
[BUG] Not compatible with pdf files edited by PDF Expert

### ISSUE THREAD

**Issue by xssworm** [unidoc/unipdf#68]
## Description
use the example pdf_extract_text.go and pdf_search_replace.go, an error will be reported during execution 'Error: unexpected EOF'

**Comment by gunnsth** [comment]
@xssworm Please include an example PDF file so that the issue can be reproduced.

**Comment by xssworm** [comment]
[edited_by_PDF_Expert.pdf](https://github.com/unidoc/unipdf/files/3223477/edited_by_PDF_Expert.pdf)

####################################################################
$ go run -a pdf_extract_text.go edited_by_PDF_Expert.pdf
--------------------
PDF to text extraction:
--------------------
------------------------------
Page 1:
"..."
------------------------------
------------------------------
Page 2:
"..."
------------------------------
------------------------------
Page 3:
"..."
------------------------------
------------------------------
Page 4:
"..."
------------------------------
Error: unexpected EOF
exit status 1
$ go run -a pdf_search_replace.go edited_by_PDF_Expert.pdf o.pdf "DESIGN" "XXXXXX"
panic: unexpected EOF

goroutine 1 [running]:
main.main()
	/Users/developer/Projects/unipdf-examples/text/pdf_search_replace.go:43 +0x1f5
exit status 2
####################################################################

**Comment by xssworm** [comment]
It seems that when there is a blank page in the PDF, it will cause an error.

**Comment by gunnsth** [comment]
@xssworm Fixed

**Comment by xssworm** [comment]
Thanks.
