### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by fengweiqiang** [unidoc/unipdf#7]
Memory is blown up
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x11d2414, 0x16)
	E:/Go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc2c8000000, 0x90000000, 0x1bd7958)
	E:/Go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1bbee20, 0x8fa56000, 0x1bbee30, 0x47d2b)
	E:/Go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1bbee20, 0x47d2b, 0x0)
	E:/Go/src/runtime/mheap.go:1232 +0x42
runtime.(*mheap).allocSpanLocked(0x1bbee20, 0x47d2b, 0x1bd7968, 0xc00034fec0)
	E:/Go/src/runtime/mheap.go:1150 +0x3a7
runtime.(*mheap).alloc_m(0x1bbee20, 0x47d2b, 0x101, 0x186a0)
	E:/Go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	E:/Go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x1bbee20, 0x47d2b, 0xc000000101, 0xc0003ee380)
	E:/Go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x8fa56000, 0xc0000b0100, 0x200000004)
	E:/Go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	E:/Go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0xc00008c240)
	E:/Go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	E:/Go/src/runtime/proc.go:1153

goroutine 1121530 [running]:
runtime.systemstack_switch()
	E:/Go/src/runtime/asm_amd64.s:311 fp=0xc00f91cb48 sp=0xc00f91cb40 pc=0x455f40
runtime.mallocgc(0x8fa56000, 0x0, 0x5beedf00, 0xc254000000)
	E:/Go/src/runtime/malloc.go:949 +0x872 fp=0xc00f91cbe8 sp=0xc00f91cb48 pc=0x40bdd2
runtime.growslice(0x106c040, 0xc254000000, 0x1cbaa7ff, 0x1cbaa800, 0x1cbaa802, 0xc254000000, 0x16fbb7ff, 0x1cbaa800)
	E:/Go/src/runtime/slice.go:175 +0x151 fp=0xc00f91cc50 sp=0xc00f91cbe8 pc=0x4415f1
github.com/unidoc/unidoc/pdf/model.(*PdfColorspaceDeviceGray).ImageToRGB(0xc000c9ef38, 0x33bc, 0x555c, 0x1, 0x1, 0xc020642000, 0x2282b20, 0x2282b20, 0x0, 0x0, ...
)
	D:/gopakge/src/github.com/unidoc/unidoc/pdf/model/colorspace.go:292 +0x1c2 fp=0xc00f91ce40 sp=0xc00f91cc50 pc=0xeb04b2
github.com/unidoc/unidoc/pdf/model.(*PdfColorspaceICCBased).ImageToRGB(0xc0109c8300, 0x33bc, 0x555c, 0x1, 0x1, 0xc020642000, 0x2282b20, 0x2282b20, 0x0, 0x0, ...)
	D:/gopakge/src/github.com/unidoc/unidoc/pdf/model/colorspace.go:1916 +0x6e1 fp=0xc00f91d128 sp=0xc00f91ce40 pc=0xebd311
service.extractImagesInContentStream(0xc000028400, 0x3d, 0xc0004c4000, 0x0, 0x0, 0x10ef280, 0x1, 0xc000834ba0)

[2045099999C717     5.18-1备26-59 溜槽 x1-05-60.zip](https://github.com/unidoc/unidoc/files/3196041/2045099999C717.5.18-1.26-59.x1-05-60.zip)

**Comment by adrg** [comment]
@fengweiqiang Thank you for reporting the issue. 

We added an optimization (PR #117) which does solve a part of the issue. However, this needs further investigation. We opened issue #116  to plan a course of action in order to optimize memory management of images so you might want to follow the progress on that issue.

**Comment by gunnsth** [comment]
@adrg This has been further addressed in PR #149.  Can we close this now?

**Comment by fengweiqiang** [comment]
enne
