### ISSUE TITLE
[BUG] Search and replace Japanese text is not supported

### ISSUE THREAD

**Issue by xssworm** [unidoc/unipdf#83]
## Description
English pdf can be searched and replaced normally. But Japanese pdf cannot be supported.

## Expected Behavior
replace the text '取扱説明書' in page 1 use this example:
https://github.com/unidoc/unipdf-examples/blob/v3/text/pdf_search_replace.go 

## Actual Behavior
$ go run pdf_search_replace.go quietcontrol-30_ja.pdf output.pdf "取扱説明書" "xxxxxx"
Successfully created output.pdf

## Descrption
Nothing changed in output.pdf. So I change some code in example:

<img width="933" alt="debug" src="https://user-images.githubusercontent.com/2535068/59186606-d6bbb000-8ba5-11e9-851f-ac536d863743.png">

## Attachments
[quietcontrol-30_ja.pdf](https://github.com/unidoc/unipdf/files/3271417/quietcontrol-30_ja.pdf)

<img width="424" alt="replace_text" src="https://user-images.githubusercontent.com/2535068/59186704-2601e080-8ba6-11e9-8abd-1f94abd44bb3.png">

**Comment by gunnsth** [comment]
@xssworm This can now be done with a more advanced search replace code.
https://github.com/unidoc/unipdf-examples/blob/development/text/pdf_search_replace_advanced.go

**Comment by xssworm** [comment]
Thanks a lot, the text replace func is ok now. But the table of contents will lost when I replace some text.
