### ISSUE TITLE
Support for search replace

### ISSUE THREAD

**Issue by ahall** [unidoc/unipdf#9]

**Comment by gunnsth** [comment]
The newest code for this:
https://github.com/unidoc/unipdf-examples/blob/master/text/pdf_search_replace.go
In the future it would be nice to have a way to do the search / replace easily with a high level interface.
The extractor package could provide the search function and then can either modify the content stream or use creator package to do the replacement.

**Comment by gunnsth** [comment]
Related to #24 redaction ticket as redaction is basically removing the underlying text from the content and putting some rectangles over it and connection with Redaction annotations.

**Comment by kellemNegasi** [comment]
Search and replace features are implemented in [v3.65.0](https://github.com/unidoc/unipdf/releases/tag/v3.65.0) and usage examples are provided [here](https://github.com/unidoc/unipdf-examples/blob/master/search-and-replace/replace_text.go) and [here](https://github.com/unidoc/unipdf-examples/blob/master/search-and-replace/search_text.go)
