### ISSUE TITLE
[BUG] go dep ensure not working

### ISSUE THREAD

**Issue by FourShore** [unidoc/unipdf#99]
## Description
Unable to find packages when running go dep ensure

## Expected Behavior
Be able to use dep ensure to get packages

## Actual Behavior
`
Solving failure: No versions of github.com/unidoc/unipdf met constraints:
	v3.0.2: "github.com/unidoc/unipdf/core" imports "github.com/unidoc/unipdf/v3/common", which contains malformed code: unknown error for "github.com/unidoc/unipdf/v3/common", if you get this error see https://github.com/golang/dep/issues/351
	v3.0.1: Could not introduce github.com/unidoc/unipdf@v3.0.1, as it is not allowed by constraint ^3.0.2 from project app.
	v3.0.0: Could not introduce github.com/unidoc/unipdf@v3.0.0, as it is not allowed by constraint ^3.0.2 from project app.
	master: Could not introduce github.com/unidoc/unipdf@master, as it is not allowed by constraint ^3.0.2 from project app.
	development: Could not introduce github.com/unidoc/unipdf@development, as it is not allowed by constraint ^3.0.2 from project app.
	license-more: Could not introduce github.com/unidoc/unipdf@license-more, as it is not allowed by constraint ^3.0.2 from project app.
	v2: Could not introduce github.com/unidoc/unipdf@v2, as it is not allowed by constraint ^3.0.2 from project app.
	v3-render-support: Could not introduce github.com/unidoc/unipdf@v3-render-support, as it is not allowed by constraint ^3.0.2 from project app.
	v3-truetype-pkg: Could not introduce github.com/unidoc/unipdf@v3-truetype-pkg, as it is not allowed by constraint ^3.0.2 from project app.
`

**Comment by gunnsth** [comment]
We will take a look at this. The depfile was added a long time ago and not really maintained.  We will see if we can update it easily, or otherwise we may drop the support and focus on support for go modules.

**Comment by adrg** [comment]
We updated the dep file. It does not solve the problem though. The issue seems related to https://github.com/golang/dep/issues/351 and https://github.com/golang/dep/issues/2139.

**Comment by gunnsth** [comment]
Closing as the bug is not on our end.
